#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Omnicx.WebStore;
    using Omnicx.WebStore.Core;
    
    #line 13 "..\..\Views\Checkout\Layout1\_CheckoutDeliveryAddress.cshtml"
    using Omnicx.WebStore.Core.Helpers;
    
    #line default
    #line hidden
    
    #line 14 "..\..\Views\Checkout\Layout1\_CheckoutDeliveryAddress.cshtml"
    using Omnicx.WebStore.Framework.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Checkout/Layout1/_CheckoutDeliveryAddress.cshtml")]
    public partial class _Views_Checkout_Layout1__CheckoutDeliveryAddress_cshtml : Omnicx.WebStore.Core.Services.Infrastructure.CustomBaseViewPage<Omnicx.WebStore.Models.Commerce.AddressModel>
    {
        public _Views_Checkout_Layout1__CheckoutDeliveryAddress_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Checkout\Layout1\_CheckoutDeliveryAddress.cshtml"
  
/*
    Name: Standard Checkout Delivery Address
    Purpose: Standard Checkout Delivery Address
    Structure: /Views/Checkout/Layout1/StandardCheckout.cshtml
    Contains (Partial Views Used):
        a-/Views/Checkout/Layout1/_CheckoutDeliveryAddressForm.cshtml   (Select Delivery Address)

    Contained In (Where we Use this View):
        a-/Views/Basket/Layout1/StandardCheckout.cshtml
    */

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 16 "..\..\Views\Checkout\Layout1\_CheckoutDeliveryAddress.cshtml"
  
    var addressForm = Html.Angular().ModelFor("ck.model.checkout.shippingAddress");

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" ng-show=\"ck.deliverAddress\"");

WriteAttribute("ng-init", Tuple.Create(" ng-init=\"", 754), Tuple.Create("\"", 852)
, Tuple.Create(Tuple.Create("", 764), Tuple.Create("showDeliveryOption=false;ck.deliverAddress=\'", 764), true)
            
            #line 20 "..\..\Views\Checkout\Layout1\_CheckoutDeliveryAddress.cshtml"
                   , Tuple.Create(Tuple.Create("", 808), Tuple.Create<System.Object, System.Int32>(SessionContext.CurrentUser
            
            #line default
            #line hidden
, 808), false)
, Tuple.Create(Tuple.Create("", 835), Tuple.Create("\'==\'\'?false:true;", 835), true)
);

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12\"");

WriteLiteral(">\r\n        <h2");

WriteLiteral(" class=\"checkout-h2\"");

WriteLiteral(" ng-hide=\"showNewAddressForm==true\"");

WriteLiteral(">Select a delivery address</h2>\r\n        <p");

WriteLiteral(" class=\"checkout-text hidden-xs\"");

WriteLiteral(">Is the address you\'d like to use displayed below? If so, click the corresponding" +
" \"Deliver to this address\" button. Or you can enter a new delivery address. </p>" +
"\r\n        <a");

WriteLiteral(" class=\"btn btn-back-link\"");

WriteLiteral(" ng-init=\"showNewAddressForm=false\"");

WriteLiteral(" ng-hide=\"showNewAddressForm==false\"");

WriteLiteral(" ng-click=\"showNewAddressForm=false\"");

WriteLiteral(">Back <i");

WriteLiteral(" class=\"fa fa-angle-left pull-left\"");

WriteLiteral("></i></a>\r\n        <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 no-padding checkoutStepShipping\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"checkout-address col-sm-4 col-xs-12 \"");

WriteLiteral(" ng-repeat=\"add in ck.userAddresses\"");

WriteLiteral(" ng-hide=\"showNewAddressForm==true\"");

WriteLiteral(" ng-class=\"ck.address== add ? \'activeAddress\' : \'\'\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-2 col-xs-2 visible-xs\"");

WriteLiteral(" ng-init=\'$index == 0 ? ck.address = add : \" \"\'");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control control--radio margin-bottom-lg\"");

WriteLiteral(" ng-click=\"ck.address=add\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"address\"");

WriteLiteral(" name=\"address\"");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" ng-checked=\"$index==0 ? true : false\"");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"control__indicator\"");

WriteLiteral("></div>\r\n                    </label>\r\n                </div>\r\n                <d" +
"iv");

WriteLiteral(" class=\"col-sm-12 col-xs-10\"");

WriteLiteral(">\r\n                    <h4");

WriteLiteral(" class=\"checkout-address-name\"");

WriteLiteral("><span");

WriteLiteral(" ng-bind=\"add.firstName\"");

WriteLiteral("></span>&nbsp;<span");

WriteLiteral(" ng-bind=\"add.lastName\"");

WriteLiteral("></span></h4>\r\n                    <p");

WriteLiteral(" class=\"checkout-address-text\"");

WriteLiteral(" ng-bind=\"add.address1\"");

WriteLiteral("></p>\r\n                    <p");

WriteLiteral(" class=\"checkout-address-text\"");

WriteLiteral(" ng-bind=\"add.address2\"");

WriteLiteral("></p>\r\n                    <p");

WriteLiteral(" class=\"checkout-address-text\"");

WriteLiteral(" ng-bind=\"add.city\"");

WriteLiteral("></p>\r\n                    <p");

WriteLiteral(" class=\"checkout-address-text\"");

WriteLiteral(" ng-bind=\"add.postCode\"");

WriteLiteral("></p>\r\n                    <p");

WriteLiteral(" class=\"checkout-address-text\"");

WriteLiteral(" ng-bind=\"add.country\"");

WriteLiteral("></p>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 margin-top-sm address-button-hidden\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"btn btn-checkout width-full\"");

WriteLiteral(" ng-click=\"ck.continueToDelivery(add);ck.ValidateDeliveryMethod();\"");

WriteLiteral(">Deliver to this address <i");

WriteLiteral(" class=\"fa fa-caret-right\"");

WriteLiteral("></i></a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-6 col-xs-6 margin-top-md address-button-hidden\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"btn btn-default width-full \"");

WriteLiteral(" ng-click=\"ck.model.checkout.shippingAddress=add\"");

WriteLiteral(">Edit</a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-6 col-xs-6 margin-top-md address-button-hidden\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"btn btn-default width-full\"");

WriteLiteral(" ng-click=\"ck.deleteAddress(add)\"");

WriteLiteral(">Delete</a>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"or-spacer\"");

WriteLiteral("><div");

WriteLiteral(" class=\"mask\"");

WriteLiteral("></div></div>\r\n            <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 no-padding visible-xs\"");

WriteLiteral(" ng-hide=\"showNewAddressForm==true\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"btn btn-new-address-link\"");

WriteLiteral(" ng-click=\"showNewAddressForm=true\"");

WriteLiteral(">Add New Address <i");

WriteLiteral(" class=\"fa fa-angle-right pull-right\"");

WriteLiteral("></i></a>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 no-padding hidden-xs\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 56 "..\..\Views\Checkout\Layout1\_CheckoutDeliveryAddress.cshtml"
           Write(Html.Partial("~/Views/Checkout/Layout1/_CheckoutDeliveryAddressForm.cshtml", @Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 no-padding visible-xs\"");

WriteLiteral(" ng-show=\"showNewAddressForm==true\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"delivery-form\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 60 "..\..\Views\Checkout\Layout1\_CheckoutDeliveryAddress.cshtml"
               Write(Html.Partial("~/Views/Checkout/Layout1/_CheckoutDeliveryAddressForm.cshtml", @Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div> \r\n</div>" +
"");

        }
    }
}
#pragma warning restore 1591
