namespace Omnicx.WebStore.Models.Enums
{
    public enum SiteViewComponentTypes
    {
        Image = 1,
        ImageGallery = 2,
        Slider = 3,
        List = 4,
        JsSnippet = 5,
        ContentBlock = 6,
        StaticHtml = 7,
        Navbar = 8,
        BlogHeader = 11,
        PageHeader = 12,
        Paragraph = 13,
        VideoGallery = 17,
        Tabs = 42,
        BrandList = 51,
        ProductList = 52,
        CategoryList = 53,
        BlogList = 54,
        Heading = 71,
        ImageText = 72,
        VideoText = 73,
        ImageTextList = 74,
        VideoTextList = 75,
        HeadingParagraph = 76,
        HeadingSubHeading = 77,
        HeadingSubHeadingParagraph = 78,
        HeadingSubHeadingWidgetList = 79,
        TabWidgetList = 80,
        Recommendation = 90,
        FeatureData = 101,
        FeatureParagraph = 102,
        FeatureServices = 103,
        FeatureListFilters = 104,
        FeatureBlogDetail = 105,
        FeatureBlogHighlightPara = 106,
        FeatureBlogBlockquote = 107,
        FeatureParagraphList = 108
    }
}
