#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Omnicx.WebStore;
    using Omnicx.WebStore.Core;
    
    #line 13 "..\..\Views\Basket\_HeaderBasketView.cshtml"
    using Omnicx.WebStore.Models.Enums;
    
    #line default
    #line hidden
    
    #line 14 "..\..\Views\Basket\_HeaderBasketView.cshtml"
    using Omnicx.WebStore.Models.Keys;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Basket/_HeaderBasketView.cshtml")]
    public partial class _Views_Basket__HeaderBasketView_cshtml : Omnicx.WebStore.Core.Services.Infrastructure.CustomBaseViewPage<dynamic>
    {
        public _Views_Basket__HeaderBasketView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Basket\_HeaderBasketView.cshtml"
  
    /*
        Name: Mini Basker
        Purpose: Show limited Information for added items in mini-cart
        Structure: /Views/Basket/_HeaderBasketView.cshtml
        Contains (Partial Views Used):
            a-/Views/Basket/_QuickOrderPad.cshtml
            b-/Views/Basket/_BulkOrderMessage.cshtml
        Contained In (Where we Use this View):
            a-/Views/Shared/_HeaderLayout.cshtml    (Link in Top Header)
        */

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 16 "..\..\Views\Basket\_HeaderBasketView.cshtml"
  

    var checkoutUrl = Url.Action("OnePageCheckout", "Checkout");
    if (ConfigKeys.OnePageCheckout == false)
    {
        checkoutUrl = Url.Action("StandardCheckout", "Checkout");
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"top-login-cart metaLinks\"");

WriteLiteral(" ng-init=\"gm.initBasket()\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"list-inline\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"shopping-cart cartopen\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1001), Tuple.Create("\"", 1038)
            
            #line 28 "..\..\Views\Basket\_HeaderBasketView.cshtml"
, Tuple.Create(Tuple.Create("", 1008), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Basket")
            
            #line default
            #line hidden
, 1008), false)
);

WriteLiteral(" class=\"metaLinks__basket minicart-custom\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"metaLinks__basket__full\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-shopping-cart\"");

WriteLiteral("></i> ");

            
            #line 29 "..\..\Views\Basket\_HeaderBasketView.cshtml"
                                                                                     Write(LT("YourBag.Text.Cart", "Cart"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                <span");

WriteLiteral(" class=\"metaLinks__basket__indicator\"");

WriteLiteral(" ng-if=\"gm.count==0\"");

WriteLiteral(">");

            
            #line 30 "..\..\Views\Basket\_HeaderBasketView.cshtml"
                                                                          Write(LT("YourBag.Text.Zero", "0"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                <span");

WriteLiteral(" class=\"metaLinks__basket__indicator\"");

WriteLiteral(" ng-if=\"gm.count>0\"");

WriteLiteral(" ng-bind=\"gm.count\"");

WriteLiteral("></span>\r\n            </a>\r\n            <ul");

WriteLiteral(" id=\"miniBasket\"");

WriteLiteral(" class=\"submenu-mainmenu cart-group-1\"");

WriteLiteral(" ng-show=\"gm.basketResponse.lineItems.length>0\"");

WriteLiteral(">\r\n                <li>\r\n                    <ul");

WriteLiteral(" id=\"cartdropdown\"");

WriteLiteral(">\r\n                        <li");

WriteLiteral(" class=\"single-cart-item clearfix\"");

WriteLiteral(" ng-repeat=\"items in gm.basketResponse.lineItems track by $index\"");

WriteLiteral(" ng-if=\'items.parentProductId == gm.emptyGuid\'");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" ng-if=\"items.parentProductId == gm.emptyGuid\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 no-padding\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-sm-3 col-xs-3 no-padding\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"cart-img\"");

WriteLiteral(">\r\n                                            <a");

WriteLiteral(" ng-href=\"/{{items.slug}}\"");

WriteLiteral(">\r\n                                                <img");

WriteLiteral(" ng-src=\"{{items.image}}\"");

WriteLiteral(" onerror=\"this.src = DEFAULT_IMAGE_URL\"");

WriteLiteral(">\r\n                                            </a>\r\n                            " +
"            </span>\r\n                                    </div>\r\n               " +
"                     <div");

WriteLiteral(" class=\"col-sm-9 col-xs-9 no-padding\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"trash-cart\"");

WriteLiteral(">\r\n                                            <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" class=\"remove\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2673), Tuple.Create("\"", 2717)
            
            #line 48 "..\..\Views\Basket\_HeaderBasketView.cshtml"
, Tuple.Create(Tuple.Create("", 2681), Tuple.Create<System.Object, System.Int32>(LT("YourBag.Text.Remove", "Remove")
            
            #line default
            #line hidden
, 2681), false)
);

WriteLiteral(" ng-click=\"gm.addToBasket(items.productId,0,items.displayOrder)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-trash-o\"");

WriteLiteral("></i></a>\r\n                                        </span>\r\n                     " +
"                   <span");

WriteLiteral(" class=\"cart-info\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"col-sm-12 col-xs-12 no-padding\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" class=\"cart-product-name\"");

WriteLiteral(" ng-href=\"/{{items.slug}}\"");

WriteLiteral(" ng-bind=\"items.name\"");

WriteLiteral("></a>\r\n                                            </span>\r\n                     " +
"                       <span");

WriteLiteral(" class=\"col-sm-12 col-xs-12 no-padding\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" ng-bind=\"items.price.formatted.withTax\"");

WriteLiteral("></span>\r\n                                            </span>\r\n                  " +
"                          <span");

WriteLiteral(" class=\"col-sm-12 col-xs-12 no-padding\"");

WriteLiteral(">                                                \r\n                              " +
"                  <button");

WriteLiteral(" class=\"btn-cart\"");

WriteLiteral(" ng-init=\"oldQty=items.qty\"");

WriteLiteral(" ng-click=\"gm.addToBasket(items.productId,-1,items.displayOrder)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-minus\"");

WriteLiteral("></i></button>\r\n                                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-mousedown=\"oldQty=items.qty\"");

WriteLiteral(" ng-model=\"items.qty\"");

WriteLiteral(" value=\"{{items.qty}}\"");

WriteLiteral(" class=\"cart-text form-control\"");

WriteLiteral(" ng-click=\"gm.onTextFocus($event)\"");

WriteLiteral(" ng-blur=\"gm.updateQtyAndAdd(items.productId,items.qty,oldQty,items.displayOrder)" +
"\"");

WriteLiteral(" numbers-Only>\r\n                                                <button");

WriteLiteral(" class=\"btn-cart\"");

WriteLiteral(" ng-click=\"gm.addToBasket(items.productId,1,items.displayOrder)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-plus\"");

WriteLiteral("></i></button>\r\n                                                <span");

WriteLiteral(" class=\"bag-price\"");

WriteLiteral(" ng-bind=\"items.totalPrice.formatted.withTax\"");

WriteLiteral("></span>\r\n                                            </span>\r\n                  " +
"                      </span>\r\n                                        ");

WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 padding-sm\"");

WriteLiteral(">\r\n                                                <strong");

WriteLiteral(" class=\"text-orange\"");

WriteAttribute("ng-show", Tuple.Create(" ng-show=\"", 4787), Tuple.Create("\"", 4870)
, Tuple.Create(Tuple.Create("", 4797), Tuple.Create("items.displayInBasket", 4797), true)
, Tuple.Create(Tuple.Create(" ", 4818), Tuple.Create("&&", 4819), true)
, Tuple.Create(Tuple.Create(" ", 4821), Tuple.Create("items.itemType", 4822), true)
, Tuple.Create(Tuple.Create(" ", 4836), Tuple.Create("==", 4837), true)
            
            #line 67 "..\..\Views\Basket\_HeaderBasketView.cshtml"
                                               , Tuple.Create(Tuple.Create("", 4839), Tuple.Create<System.Object, System.Int32>(ItemTypes.Bundle.GetHashCode()
            
            #line default
            #line hidden
, 4839), false)
);

WriteLiteral(">");

            
            #line 67 "..\..\Views\Basket\_HeaderBasketView.cshtml"
                                                                                                                                                           Write(LT("YourBag.Text.IncludeComponents", "Included Components:"));

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                                                <div");

WriteLiteral(" class=\"row component-row\"");

WriteLiteral(" ng-repeat=\"bundle in gm.basketResponse.lineItems track by $index\"");

WriteLiteral(" ng-if=\"bundle.parentProductId == items.productId\"");

WriteLiteral(" ng-show=\"items.displayInBasket\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"col-sm-9 col-xs-9 no-padding\"");

WriteLiteral(">\r\n                                                        <a");

WriteLiteral(" class=\"cart-product-name\"");

WriteLiteral(" ng-href=\"/{{bundle.slug}}\"");

WriteLiteral(" ng-bind=\"bundle.name\"");

WriteLiteral("></a>\r\n                                                    </div>\r\n              " +
"                                      <div");

WriteLiteral(" class=\"col-sm-3 col-xs-3 no-padding text-right\"");

WriteLiteral(">\r\n                                                        <strong>");

            
            #line 73 "..\..\Views\Basket\_HeaderBasketView.cshtml"
                                                           Write(LT("YourBag.Text.Qty", "Qty:"));

            
            #line default
            #line hidden
WriteLiteral(" </strong><span");

WriteLiteral(" ng-bind=\"bundle.qty\"");

WriteLiteral(@"></span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            ");

WriteLiteral("\r\n                            <ul");

WriteLiteral(" id=\"cartdropdownFree\"");

WriteLiteral(">\r\n                                <li");

WriteLiteral(" ng-repeat=\"freeitem in gm.basketResponse.lineItems track by $index\"");

WriteLiteral(" ng-if=\"freeitem.parentProductId == items.productId && items.itemType!=7\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 no-padding\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"col-sm-3 col-xs-3 no-padding\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"cart-img\"");

WriteLiteral(">\r\n                                                    <a");

WriteLiteral(" ng-href=\"/{{freeitem.slug}}\"");

WriteLiteral(">\r\n                                                        <img");

WriteLiteral(" ng-src=\"{{freeitem.image}}\"");

WriteLiteral(" onerror=\"this.src = DEFAULT_IMAGE_URL\"");

WriteLiteral(">\r\n                                                    </a>\r\n                    " +
"                            </span>\r\n                                           " +
" </div>\r\n                                            <div");

WriteLiteral(" class=\"col-sm-9 col-xs-9 no-padding\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"cart-info\"");

WriteLiteral(">\r\n                                                    <a");

WriteLiteral(" class=\"cart-product-name\"");

WriteLiteral(" ng-href=\"/{{freeitem.slug}}\"");

WriteLiteral(" ng-bind=\"freeitem.name\"");

WriteLiteral("></a>\r\n                                                    <span");

WriteLiteral(" class=\"pull-right text-right\"");

WriteLiteral(">\r\n                                                        <span");

WriteLiteral(" ng-show=\"freeitem.price.raw.withTax==0\"");

WriteLiteral(">");

            
            #line 97 "..\..\Views\Basket\_HeaderBasketView.cshtml"
                                                                                                 Write(LT("YourBag.Text.Free", "FREE"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                                        <span");

WriteLiteral(" ng-hide=\"freeitem.price.raw.withTax==0\"");

WriteLiteral(" ng-bind=\"freeitem.price.formatted.withTax\"");

WriteLiteral("></span>\r\n                                                    </span>\r\n          " +
"                                          <span");

WriteLiteral(" class=\"pull-right text-right\"");

WriteLiteral(">&times;</span>\r\n                                                    <span");

WriteLiteral(" class=\"pull-right text-right\"");

WriteLiteral(" ng-bind=\"freeitem.qty\"");

WriteLiteral(@"></span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li ng-cloak");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(" style=\"float:right;\"");

WriteLiteral(" ng-show=\"gm.errorMessage\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i><span");

WriteLiteral(" ng-bind=\"gm.errorMessage\"");

WriteLiteral("></span>\r\n                </li>\r\n                <li>\r\n                    <selec" +
"t");

WriteLiteral(" id=\"deliverydrpdwn\"");

WriteLiteral(" ng-model=\"selectedid\"");

WriteLiteral(" ng-change=\"gm.updateShipping(selectedid)\"");

WriteLiteral(">\r\n                        <option");

WriteLiteral(" ng-repeat=\"methods in gm.basketResponse.shippingMethods track by $index\"");

WriteLiteral(" ng-selected=\"methods.id == gm.basketResponse.shippingMethodId\"");

WriteLiteral(" ng-model=\"methods.id\"");

WriteLiteral(" id=\"{{methods.id}}\"");

WriteLiteral(" ng-value=\"methods.id\"");

WriteLiteral(" ng-bind=\"methods.displayName +\' \' + \'(\' + methods.price.formatted.withTax + \')\'\"" +
"");

WriteLiteral("></option>\r\n                    </select>\r\n                </li>\r\n               " +
" <li");

WriteLiteral(" class=\"total-amount sub_total_price\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"sub-total-cart amount shopping-cart__total total col-lg-12 no-padding\"");

WriteLiteral(">\r\n                        <form");

WriteLiteral(" ng-submit=\"gm.applyPromoCode(gm.basketResponse.id,promoCode)\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"input-group basket-coupon-width\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"promoCode\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 9521), Tuple.Create("\"", 9605)
            
            #line 123 "..\..\Views\Basket\_HeaderBasketView.cshtml"
                          , Tuple.Create(Tuple.Create("", 9535), Tuple.Create<System.Object, System.Int32>(LT("YourBag.Text.PlaceHolder.Enterpromotioncode", "Enter Promo Code")
            
            #line default
            #line hidden
, 9535), false)
);

WriteLiteral(" style=\"width: 99%;\"");

WriteLiteral(" />\r\n                                <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" class=\"btn btn-checkout\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" ng-click=\"gm.applyPromoCode(gm.basketResponse.id,promoCode)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-gift\"");

WriteLiteral("></i></button>\r\n                                </span>\r\n                        " +
"        <span ng-cloak");

WriteLiteral(" class=\"alert alert-danger promo pull-left col-lg-12\"");

WriteLiteral(" ng-show=\"gm.showCustomMsg\"");

WriteLiteral(">{{gm.customMsg}}</span>\r\n                                <span ng-cloak");

WriteLiteral(" class=\"alert alert-danger promo pull-left col-lg-12\"");

WriteLiteral(" ng-show=\"gm.invalidpromo && !gm.showCustomMsg\"");

WriteLiteral(">");

            
            #line 128 "..\..\Views\Basket\_HeaderBasketView.cshtml"
                                                                                                                                              Write(LT("Checkout.Text.InValidPromoMessage", "PromoCode Invalid!"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                <span ng-cloak");

WriteLiteral(" class=\"alert alert-success promovalid pull-left col-lg-12\"");

WriteLiteral(" ng-show=\"gm.validpromo\"");

WriteLiteral(">");

            
            #line 129 "..\..\Views\Basket\_HeaderBasketView.cshtml"
                                                                                                                             Write(LT("Checkout.Text.ValidPromoMessage", "Successfully Applied"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                <span ng-cloak");

WriteLiteral(" class=\"alert alert-danger promonull pull-left col-lg-12\"");

WriteLiteral(" ng-show=\"gm.promonull\"");

WriteLiteral(">");

            
            #line 130 "..\..\Views\Basket\_HeaderBasketView.cshtml"
                                                                                                                          Write(LT("Checkout.Text.NullPromoMessage", "Please enter promo code!"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                            </div>\r\n                        </form>\r\n   " +
"                 </div>\r\n                    <div");

WriteLiteral(" class=\"sub-total-cart amount shopping-cart__total total col-lg-12 no-padding\"");

WriteLiteral(" id=\"promoApplied\"");

WriteLiteral(" ng-show=\"gm.basketResponse.promotionsApplied.length>0\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12 no-padding\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" class=\"basket-price\"");

WriteLiteral(">");

            
            #line 136 "..\..\Views\Basket\_HeaderBasketView.cshtml"
                                               Write(LT("Checkout.Text.PromotionApplied", "Promotion Applied"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-sm-12 no-padding\"");

WriteLiteral(">\r\n                            <ul>\r\n                                <li");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(" ng-repeat=\"promotion in gm.basketResponse.promotionsApplied track by $index\"");

WriteLiteral(">\r\n                                    <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" class=\"promoApply\"");

WriteLiteral(" title=\"Remove\"");

WriteLiteral(" ng-click=\"gm.removePromoCode(gm.basketResponse.id,promotion.promoCode)\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" ng-bind=\"promotion.name\"");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral("></span>\r\n                                        <i");

WriteLiteral(" class=\"fa fa-remove pull-right promoRemove\"");

WriteLiteral("></i>\r\n                                    </a>\r\n                                " +
"</li>\r\n                            </ul>\r\n                        </div>\r\n      " +
"              </div>\r\n                    <div");

WriteLiteral(" class=\"sub-total-cart amount shopping-cart__total total col-lg-12 no-padding\"");

WriteLiteral(">\r\n                        <p");

WriteLiteral(" class=\"basket-price\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 151 "..\..\Views\Basket\_HeaderBasketView.cshtml"
                       Write(LT("YourBag.Text.Discount", "Discount"));

            
            #line default
            #line hidden
WriteLiteral(": <span");

WriteLiteral(" class=\"money\"");

WriteLiteral(" data-currency-usd=\"$48.00\"");

WriteLiteral(" data-currency-eur=\"&amp;euro;45.42\"");

WriteLiteral(" data-currency=\"EUR\"");

WriteLiteral(" ng-bind=\"gm.basketResponse.discount.formatted.withTax\"");

WriteLiteral("></span>\r\n                        </p>\r\n                    </div>\r\n             " +
"       <div");

WriteLiteral(" class=\"sub-total-cart amount shopping-cart__total total col-lg-12 no-padding\"");

WriteLiteral(">\r\n                        <p");

WriteLiteral(" class=\"basket-price\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 156 "..\..\Views\Basket\_HeaderBasketView.cshtml"
                       Write(LT("YourBag.Text.GrandTotal", "Order Total"));

            
            #line default
            #line hidden
WriteLiteral(": <span");

WriteLiteral(" class=\"money\"");

WriteLiteral(" data-currency-usd=\"$48.00\"");

WriteLiteral(" data-currency-eur=\"&amp;euro;45.42\"");

WriteLiteral(" data-currency=\"EUR\"");

WriteLiteral(" ng-bind=\"gm.basketResponse.grandTotal.formatted.withTax\"");

WriteLiteral("></span>\r\n                        </p>\r\n                    </div>\r\n\r\n           " +
"         <div");

WriteLiteral(" class=\"sub-total-cart amount shopping-cart__total total col-lg-12 no-padding\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-6 col-xs-12 no-padding-left\"");

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 13040), Tuple.Create("\"", 13077)
            
            #line 162 "..\..\Views\Basket\_HeaderBasketView.cshtml"
, Tuple.Create(Tuple.Create("", 13047), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Basket")
            
            #line default
            #line hidden
, 13047), false)
);

WriteLiteral(" class=\"animate btn-bordered\"");

WriteLiteral(">");

            
            #line 162 "..\..\Views\Basket\_HeaderBasketView.cshtml"
                                                                                             Write(LT("Header.Link.ViewCart", "View Cart"));

            
            #line default
            #line hidden
WriteLiteral(" <i");

WriteLiteral(" class=\"fa fa-caret-right\"");

WriteLiteral("></i></a>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-sm-6 col-xs-12\"");

WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 13308), Tuple.Create("\"", 13353)
            
            #line 165 "..\..\Views\Basket\_HeaderBasketView.cshtml"
, Tuple.Create(Tuple.Create("", 13315), Tuple.Create<System.Object, System.Int32>(checkoutUrl
            
            #line default
            #line hidden
, 13315), false)
, Tuple.Create(Tuple.Create("", 13327), Tuple.Create("//{{gm.basketResponse.id}}", 13327), true)
);

WriteLiteral(" class=\"animate btn-orange\"");

WriteLiteral(">");

            
            #line 165 "..\..\Views\Basket\_HeaderBasketView.cshtml"
                                                                                                   Write(LT("Checkout.Title.PlaceOrder", "Place Order"));

            
            #line default
            #line hidden
WriteLiteral(" <i");

WriteLiteral(" class=\"fa fa-caret-right\"");

WriteLiteral("></i></a>\r\n                        </div>\r\n                    </div>\r\n          " +
"      </li>\r\n            </ul>\r\n        </li>\r\n    </ul>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
