#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Omnicx.WebStore;
    using Omnicx.WebStore.Core;
    
    #line 13 "..\..\Views\Account\ForgotPassword.cshtml"
    using Omnicx.WebStore.Framework.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ForgotPassword.cshtml")]
    public partial class _Views_Account_ForgotPassword_cshtml : Omnicx.WebStore.Core.Services.Infrastructure.CustomBaseViewPage<Omnicx.WebStore.Models.Commerce.ForgotPasswordModel>
    {
        public _Views_Account_ForgotPassword_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Account\ForgotPassword.cshtml"
  
/*
    Name: Forgot Password
    Purpose: Reset Password
    Structure: /Views/Account/ForgotPassword.cshtml
    Contains (Partial Views Used):
        a-/Views/Shared/_Layout.cshtml.cshtml    (For base Structure)

    Contained In (Where we Use this View):
        a-/Views/Account/SignIn.cshtml 
    */

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 15 "..\..\Views\Account\ForgotPassword.cshtml"
  
    var userForm = Html.Angular().ModelFor("gm.model.forgotPassword");
    ViewBag.Title = "Forgot Password";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container dataContainer m--top-60 lg\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n\r\n                <li>\r\n                    <a");

WriteLiteral(" href=\"/\"");

WriteLiteral(">");

            
            #line 26 "..\..\Views\Account\ForgotPassword.cshtml"
                           Write(LT("MyAccount.Links.Home", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </li>\r\n                <li>");

            
            #line 28 "..\..\Views\Account\ForgotPassword.cshtml"
               Write(LT("MyAccount.Text.ForgotPassword", "Forgot Password"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n            </ul>\r\n        </div>\r\n\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" role=\"form\"");

WriteLiteral(" ng-init=\"gm.returnUrl=\'/account/signin\'\"");

WriteLiteral(" ng-submit=\"gm.forgotPassword(gm.model.forgotPassword)\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(" novalidate>\r\n            <div ng-cloak");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(" ng-show=\"gm.errorMessage != null\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" ng-repeat=\"err in gm.errorMessage track by $index\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>&nbsp;<span");

WriteLiteral(" ng-bind=\"err\"");

WriteLiteral("></span>\r\n                </div>\r\n            </div>\r\n            <div ng-cloak");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(" ng-show=\"gm.isValiduser\"");

WriteLiteral(">\r\n                <div>\r\n                    <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>&nbsp;<span>");

            
            #line 44 "..\..\Views\Account\ForgotPassword.cshtml"
                                                       Write(LT("Login.Message.InvalidUser", "Invalid User!"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </div>\r\n            </div>\r\n            <div ng-cloak");

WriteLiteral(" class=\"alert alert-success\"");

WriteLiteral(" ng-show=\"gm.isValid\"");

WriteLiteral(">\r\n                <div>\r\n                    <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>&nbsp;<span>");

            
            #line 49 "..\..\Views\Account\ForgotPassword.cshtml"
                                                       Write(LT("Login.Message.ResetPassword", "Link to reset your password sent"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </div>\r\n            </div>\r\n            <h2");

WriteLiteral(" class=\"checkout-h2\"");

WriteLiteral(">");

            
            #line 52 "..\..\Views\Account\ForgotPassword.cshtml"
                               Write(LT("MyAccount.Text.ForgotPassword", "Forgot Password"));

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n            <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 no-padding form-group checkoutForm\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 54 "..\..\Views\Account\ForgotPassword.cshtml"
           Write(userForm.FormGroupFor(x => x.Username));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-sm-6 col-xs-6 no-padding\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"animate btn-primary\"");

WriteLiteral(">");

            
            #line 57 "..\..\Views\Account\ForgotPassword.cshtml"
                                                             Write(LT("MyAccount.Text.GetLink", "Get a link"));

            
            #line default
            #line hidden
WriteLiteral(" <i");

WriteLiteral(" class=\"fa fa-caret-right\"");

WriteLiteral("></i></button>\r\n            </div>\r\n        </form>\r\n    </div>\r\n</div>\r\n\r\n\r\n\r\n\r\n" +
"");

DefineSection("Scripts", () => {

            
            #line 66 "..\..\Views\Account\ForgotPassword.cshtml"
    
            
            #line default
            #line hidden
WriteLiteral("\r\n        <script>\r\n            window.app.constant(\'accountConfig\', {\r\n         " +
"   });\r\n            window.app.constant(\'model\', ");

            
            #line 70 "..\..\Views\Account\ForgotPassword.cshtml"
                                    Write(Html.JsonFor(Model));

            
            #line default
            #line hidden
WriteLiteral(");\r\n        </script>\r\n    ");

});

        }
    }
}
#pragma warning restore 1591
