#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    
    #line 1 "..\..\Views\Account\SurveyResponse.cshtml"
    using Microsoft.Web.Mvc;
    
    #line default
    #line hidden
    using Omnicx.WebStore;
    using Omnicx.WebStore.Core;
    
    #line 2 "..\..\Views\Account\SurveyResponse.cshtml"
    using Omnicx.WebStore.Core.Controllers;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Account\SurveyResponse.cshtml"
    using Omnicx.WebStore.Framework.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/SurveyResponse.cshtml")]
    public partial class _Views_Account_SurveyResponse_cshtml : Omnicx.WebStore.Core.Services.Infrastructure.CustomBaseViewPage< List <Omnicx.WebStore.Models.Site.SurveyAnswerModel>>
    {
        public _Views_Account_SurveyResponse_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Account\SurveyResponse.cshtml"
  
    ViewBag.Title = @LT("MyAccount.Text.PersonalityQuiz", "Personality Quiz");

            
            #line default
            #line hidden
WriteLiteral("\r\n    \r\n<section");

WriteLiteral(" class=\"container dataContainer m--top-60\"");

WriteLiteral(" ng-controller=\"accountCtrl as am\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n                <li>\r\n                    <a");

WriteLiteral(" href=\"/\"");

WriteLiteral(">");

            
            #line 15 "..\..\Views\Account\SurveyResponse.cshtml"
                           Write(LT("MyAccount.Links.Home", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </li>\r\n                <li>");

            
            #line 17 "..\..\Views\Account\SurveyResponse.cshtml"
               Write(LT("MyAccount.Text.PersonalityQuiz", "Personality Quiz"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-12 visible-xs\"");

WriteLiteral(" id=\"exTab1\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 23 "..\..\Views\Account\SurveyResponse.cshtml"
       Write(Html.Partial("~/Views/Account/_MobileSideNav.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-md-3 col-sm-4 col-xs-12 hidden-xs\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 26 "..\..\Views\Account\SurveyResponse.cshtml"
       Write(Html.Partial("~/Views/Account/_SideNav.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-md-9 col-sm-8 col-xs-12\"");

WriteLiteral(" id=\"customer-Quiz\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" class=\"table table-hover table-striped\"");

WriteLiteral(">\r\n                <thead>\r\n                    <tr>\r\n                        <th" +
">");

            
            #line 32 "..\..\Views\Account\SurveyResponse.cshtml"
                       Write(LT("MyAccount.Text.Name", "Name"));

            
            #line default
            #line hidden
WriteLiteral("</th>  \r\n                        <th>");

            
            #line 33 "..\..\Views\Account\SurveyResponse.cshtml"
                       Write(LT("MyAccount.Text.ResponseDate", "Response Date"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th");

WriteLiteral(" class=\"text-right\"");

WriteLiteral("></th>\r\n                    </tr>\r\n                    <tr");

WriteLiteral(" ng-repeat=\"survey in am.model\"");

WriteLiteral(">\r\n                        <td");

WriteLiteral(" ng-bind=\"survey.surveyName\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" ng-bind=\"survey.created | ocxDateTime\"");

WriteLiteral("></td>\r\n                        <td>\r\n                            <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" ng-click=\"am.showSurveyResponse(survey)\"");

WriteLiteral(" title=\"View Answers\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-eye color-black\"");

WriteLiteral("></i></a>\r\n                        </td>\r\n                    </tr>\r\n            " +
"    </thead>\r\n            </table>\r\n        </div>\r\n </div>\r\n    <div");

WriteLiteral(" class=\"modal fade in\"");

WriteLiteral(" id=\"showeSurvey\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"showeSurvey\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">×</button>\r\n                    <h3");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" ng-bind=\"am.survey.surveyName\"");

WriteLiteral("></h3>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 table-responsive form-group\"");

WriteLiteral(">                          \r\n                            <table");

WriteLiteral(" class=\"table table-hover table-striped table-bordered\"");

WriteLiteral(">\r\n                                <thead>\r\n                                    <" +
"tr>\r\n                                        <th");

WriteLiteral(" ng-repeat=\"(key, value) in am.surveyAns[0] track by $index\"");

WriteLiteral(">{{key}}</th>\r\n                                    </tr>\r\n                       " +
"         </thead>\r\n                                <tbody>\r\n                    " +
"                <tr");

WriteLiteral(" ng-repeat=\"(key, value) in am.surveyAns  track by $index\"");

WriteLiteral(">\r\n                                        <td");

WriteLiteral(" ng-repeat=\"(key, value) in value  track by $index\"");

WriteLiteral(@">
                                            {{value}}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div> 
                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</section>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script>       \r\n        window.app.constant(\'accountConfig\', {\r\n          " +
" \r\n        });\r\n        window.app.constant(\'model\', ");

            
            #line 85 "..\..\Views\Account\SurveyResponse.cshtml"
                                Write(Html.JsonFor(Model));

            
            #line default
            #line hidden
WriteLiteral(");\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
