#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    
    #line 1 "..\..\Views\Blog\Layout1\Search.cshtml"
    using Microsoft.Web.Mvc;
    
    #line default
    #line hidden
    using Omnicx.WebStore;
    using Omnicx.WebStore.Core;
    
    #line 2 "..\..\Views\Blog\Layout1\Search.cshtml"
    using Omnicx.WebStore.Core.Controllers;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Blog\Layout1\Search.cshtml"
    using Omnicx.WebStore.Core.Helpers;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Blog\Layout1\Search.cshtml"
    using Omnicx.WebStore.Framework.Helpers;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Blog\Layout1\Search.cshtml"
    using Omnicx.WebStore.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Blog/Layout1/Search.cshtml")]
    public partial class _Views_Blog_Layout1_Search_cshtml : Omnicx.WebStore.Core.Services.Infrastructure.CustomBaseViewPage<Omnicx.WebStore.Models.Site.BlogDetailViewModel>
    {
        public _Views_Blog_Layout1_Search_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 7 "..\..\Views\Blog\Layout1\Search.cshtml"
  
    ViewBag.Title = @Model.FreeText;
    Layout = "~/Views/Shared/Layout1/_LayoutBlog.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 12 "..\..\Views\Blog\Layout1\Search.cshtml"
  
/*
Name: Blog Search result page
Purpose: Show all blogs after search
Structure: /Views/Blog/Layout1/Search.cshtml
Contains (Partial Views Used):
    a-/Views/Shared/Layout1/_LayoutBlog.cshtml
Contained In (Where we Use this View) :
*/

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n    #landing-banner{\r\n        display:none!important;\r\n    }\r\n</style>" +
"\r\n<section");

WriteLiteral(" ng-controller=\"blogCtrl as bm\"");

WriteLiteral(">\r\n");

            
            #line 28 "..\..\Views\Blog\Layout1\Search.cshtml"
    
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Blog\Layout1\Search.cshtml"
       /* Start breadcrumb container */ 
            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"col-sm-12 margin-top-md\"");

WriteLiteral(">\r\n        <ul");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n            <li><a");

WriteLiteral(" href=\"/\"");

WriteLiteral(">Home</a></li>\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 961), Tuple.Create("\"", 996)
            
            #line 32 "..\..\Views\Blog\Layout1\Search.cshtml"
, Tuple.Create(Tuple.Create("", 968), Tuple.Create<System.Object, System.Int32>(Url.Action("Blogs", "Blog")
            
            #line default
            #line hidden
, 968), false)
);

WriteLiteral(">");

            
            #line 32 "..\..\Views\Blog\Layout1\Search.cshtml"
                                                  Write(LT("Blogs.Links.Blogs","Blogs"));

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li>");

            
            #line 33 "..\..\Views\Blog\Layout1\Search.cshtml"
           Write(Model.FreeText.ToCamelCase());

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        </ul>\r\n    </div>\r\n");

            
            #line 36 "..\..\Views\Blog\Layout1\Search.cshtml"
    
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Blog\Layout1\Search.cshtml"
       /* End breadcrumb container */ 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 37 "..\..\Views\Blog\Layout1\Search.cshtml"
    
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Blog\Layout1\Search.cshtml"
     if (String.IsNullOrEmpty(Model.FreeText))
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"col-sm-12 no-padding margin-top-md\"");

WriteLiteral(">\r\n            <h4");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 40 "..\..\Views\Blog\Layout1\Search.cshtml"
                               Write(LT("Blogs.Text.EmptySearch", "Oops! We cannot search for an empty value, please enter a search term."));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n        </div>\r\n");

            
            #line 42 "..\..\Views\Blog\Layout1\Search.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"blog-homepage\"");

WriteLiteral(" class=\"col-sm-12 no-padding\"");

WriteLiteral(">\r\n");

            
            #line 47 "..\..\Views\Blog\Layout1\Search.cshtml"
                
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Blog\Layout1\Search.cshtml"
                   /* Start Blog search panel */ 
            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"col-sm-12 no-padding\"");

WriteLiteral(">\r\n                    <h1");

WriteLiteral(" ng-hide=\"bm.freeText\"");

WriteLiteral(" class=\"blog-h1\"");

WriteLiteral(">");

            
            #line 49 "..\..\Views\Blog\Layout1\Search.cshtml"
                                                         Write(Model.FreeText);

            
            #line default
            #line hidden
WriteLiteral(" <a");

WriteLiteral(" ng-click=\"bm.searchAgain()\"");

WriteLiteral("><span");

WriteAttribute("ng-show", Tuple.Create(" ng-show=\'", 1778), Tuple.Create("\'", 1822)
            
            #line 49 "..\..\Views\Blog\Layout1\Search.cshtml"
                                            , Tuple.Create(Tuple.Create("", 1788), Tuple.Create<System.Object, System.Int32>(Model.BlogList.Results.Count
            
            #line default
            #line hidden
, 1788), false)
, Tuple.Create(Tuple.Create(" ", 1817), Tuple.Create("==", 1818), true)
, Tuple.Create(Tuple.Create(" ", 1820), Tuple.Create("0", 1821), true)
);

WriteLiteral(" class=\'fa fa-remove\'");

WriteLiteral("></span></a></h1>\r\n                    <form");

WriteLiteral(" ng-show=\"bm.freeSearch\"");

WriteLiteral(" action=\"/blog/search\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"text-right margin-top-2\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"search\"");

WriteLiteral(" ng-model=\"searchText\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Search blog\"");

WriteLiteral(" />\r\n                            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"currentPage\"");

WriteLiteral(" value=\"1\"");

WriteLiteral(" />\r\n                        </div>\r\n                    </form>\r\n               " +
" </div>\r\n");

            
            #line 57 "..\..\Views\Blog\Layout1\Search.cshtml"
                
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Blog\Layout1\Search.cshtml"
                   /* End Blog search panel */ 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 59 "..\..\Views\Blog\Layout1\Search.cshtml"
                
            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Blog\Layout1\Search.cshtml"
                   /* SHow if no blog matching search criteria */ 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 60 "..\..\Views\Blog\Layout1\Search.cshtml"
                
            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\Blog\Layout1\Search.cshtml"
                 if (@Model.BlogList.Results.Count == 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"col-sm-12 no-padding margin-top-md\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 63 "..\..\Views\Blog\Layout1\Search.cshtml"
                                           Write(LT("Blogs.Text.NoResultFound", "There are no results for your search term, please try again or use the navigation to make your way around the site."));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                    </div>\r\n");

            
            #line 65 "..\..\Views\Blog\Layout1\Search.cshtml"
                }
                else
                {
                    
            
            #line default
            #line hidden
            
            #line 68 "..\..\Views\Blog\Layout1\Search.cshtml"
                                  

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"col-sm-12 no-padding\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-6 no-padding\"");

WriteAttribute("ng-init", Tuple.Create(" ng-init=\'", 3024), Tuple.Create("\'", 3075)
, Tuple.Create(Tuple.Create("", 3034), Tuple.Create("bm.initCategoryResults(", 3034), true)
            
            #line 70 "..\..\Views\Blog\Layout1\Search.cshtml"
         , Tuple.Create(Tuple.Create("", 3057), Tuple.Create<System.Object, System.Int32>(Html.Json(Model)
            
            #line default
            #line hidden
, 3057), false)
, Tuple.Create(Tuple.Create("", 3074), Tuple.Create(")", 3074), true)
);

WriteLiteral(">\r\n                            <form");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" for=\"refine by\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 74 "..\..\Views\Blog\Layout1\Search.cshtml"
                                   Write(LT("productlisting.label.showing", "showing"));

            
            #line default
            #line hidden
WriteLiteral(" <strong");

WriteAttribute("ng-bind", Tuple.Create(" ng-bind=\"", 3348), Tuple.Create("\"", 3418)
, Tuple.Create(Tuple.Create("", 3358), Tuple.Create("((", 3358), true)
            
            #line 74 "..\..\Views\Blog\Layout1\Search.cshtml"
                          , Tuple.Create(Tuple.Create("", 3360), Tuple.Create<System.Object, System.Int32>(Model.BlogList.CurrentPage
            
            #line default
            #line hidden
, 3360), false)
, Tuple.Create(Tuple.Create("", 3387), Tuple.Create("-1)", 3387), true)
, Tuple.Create(Tuple.Create(" ", 3390), Tuple.Create("*", 3391), true)
            
            #line 74 "..\..\Views\Blog\Layout1\Search.cshtml"
                                                          , Tuple.Create(Tuple.Create(" ", 3392), Tuple.Create<System.Object, System.Int32>(Model.BlogList.Pages
            
            #line default
            #line hidden
, 3393), false)
, Tuple.Create(Tuple.Create("", 3414), Tuple.Create(")", 3414), true)
, Tuple.Create(Tuple.Create(" ", 3415), Tuple.Create("+1", 3416), true)
);

WriteLiteral(">\r\n                                        </strong> ");

            
            #line 75 "..\..\Views\Blog\Layout1\Search.cshtml"
                                             Write(LT("productlisting.label.to", "to"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <span");

WriteLiteral(" ng-hide=\"bm.total <(bm.currentPage * bm.pages)\"");

WriteLiteral(">\r\n                                            <strong");

WriteAttribute("ng-bind", Tuple.Create(" ng-bind=\"", 3657), Tuple.Create("\"", 3720)
, Tuple.Create(Tuple.Create("", 3667), Tuple.Create("((", 3667), true)
            
            #line 77 "..\..\Views\Blog\Layout1\Search.cshtml"
, Tuple.Create(Tuple.Create("", 3669), Tuple.Create<System.Object, System.Int32>(Model.BlogList.CurrentPage
            
            #line default
            #line hidden
, 3669), false)
, Tuple.Create(Tuple.Create("", 3696), Tuple.Create(")*", 3696), true)
            
            #line 77 "..\..\Views\Blog\Layout1\Search.cshtml"
            , Tuple.Create(Tuple.Create("", 3698), Tuple.Create<System.Object, System.Int32>(Model.BlogList.Pages
            
            #line default
            #line hidden
, 3698), false)
, Tuple.Create(Tuple.Create("", 3719), Tuple.Create(")", 3719), true)
);

WriteLiteral("></strong>\r\n                                        </span>\r\n                    " +
"                    <span");

WriteLiteral(" ng-show=\"bm.total<(bm.currentPage * bm.pages)\"");

WriteLiteral(">\r\n                                            <strong>");

            
            #line 80 "..\..\Views\Blog\Layout1\Search.cshtml"
                                               Write(Model.BlogList.Total);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                                        </span>\r\n");

WriteLiteral("                                        ");

            
            #line 82 "..\..\Views\Blog\Layout1\Search.cshtml"
                                   Write(LT("productlisting.label.of", "of"));

            
            #line default
            #line hidden
WriteLiteral(" <strong");

WriteLiteral(" ng-bind=\"bm.total\"");

WriteLiteral("></strong> ");

            
            #line 82 "..\..\Views\Blog\Layout1\Search.cshtml"
                                                                                                             Write(LT("productlisting.label.results", "results"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </label>\r\n                                <" +
"/div>\r\n                            </form>\r\n                        </div>\r\n    " +
"                    <div");

WriteLiteral(" class=\"col-sm-6 no-padding\"");

WriteLiteral(">\r\n                            <ul");

WriteLiteral(" class=\"pull-right pagination\"");

WriteLiteral(">\r\n");

            
            #line 89 "..\..\Views\Blog\Layout1\Search.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 89 "..\..\Views\Blog\Layout1\Search.cshtml"
                                 if (@Model.BlogList.Total > @Model.BlogList.Pages)
                                {
                                    for (var i = 1; i <= Convert.ToDecimal(@Model.BlogList.Total / @Model.PageSize) + 1; i++)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li");

WriteLiteral(" class=\"ng-scope\"");

WriteLiteral(">\r\n                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4845), Tuple.Create("\"", 4934)
            
            #line 94 "..\..\Views\Blog\Layout1\Search.cshtml"
, Tuple.Create(Tuple.Create("", 4852), Tuple.Create<System.Object, System.Int32>(Url.Action("search", "blog", new { search = @Model.FreeText, @currentpage = @i })
            
            #line default
            #line hidden
, 4852), false)
);

WriteLiteral(">");

            
            #line 94 "..\..\Views\Blog\Layout1\Search.cshtml"
                                                                                                                                    Write(i);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                        </li>\r\n");

            
            #line 96 "..\..\Views\Blog\Layout1\Search.cshtml"
                                    }
                                }

            
            #line default
            #line hidden
WriteLiteral("                                ");

            
            #line 98 "..\..\Views\Blog\Layout1\Search.cshtml"
                                 if (@Model.BlogList.Total == @Model.BlogList.Pages)
                                {
                                    for (var i = 1; i <= Convert.ToDecimal(@Model.BlogList.Total / @Model.PageSize); i++)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li");

WriteLiteral(" class=\"ng-scope\"");

WriteLiteral(">\r\n                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5457), Tuple.Create("\"", 5546)
            
            #line 103 "..\..\Views\Blog\Layout1\Search.cshtml"
, Tuple.Create(Tuple.Create("", 5464), Tuple.Create<System.Object, System.Int32>(Url.Action("search", "blog", new { search = @Model.FreeText, @currentpage = @i })
            
            #line default
            #line hidden
, 5464), false)
);

WriteLiteral(">");

            
            #line 103 "..\..\Views\Blog\Layout1\Search.cshtml"
                                                                                                                                    Write(i);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                        </li>\r\n");

            
            #line 105 "..\..\Views\Blog\Layout1\Search.cshtml"
                                    }
                                }
                                
            
            #line default
            #line hidden
            
            #line 112 "..\..\Views\Blog\Layout1\Search.cshtml"
                                   

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\r\n                        </div>\r\n              " +
"      </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"col-sm-12 no-padding margin-top-md\"");

WriteLiteral(">\r\n");

            
            #line 117 "..\..\Views\Blog\Layout1\Search.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 117 "..\..\Views\Blog\Layout1\Search.cshtml"
                         foreach (var item in @Model.BlogList.Results)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"col-sm-8 col-md-8 col-md-offset-2 col-sm-offset-2\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"row border-bottom-blog\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n");

            
            #line 122 "..\..\Views\Blog\Layout1\Search.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 122 "..\..\Views\Blog\Layout1\Search.cshtml"
                                         if (item.BlogImage == null)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <img");

WriteAttribute("ng-src", Tuple.Create(" ng-src=\"", 6732), Tuple.Create("\"", 6783)
, Tuple.Create(Tuple.Create("", 6741), Tuple.Create<System.Object, System.Int32>(Href("~/assets/theme/ocx/images/noimagefound.jpg")
, 6741), false)
);

WriteLiteral(" class=\"img-responsive\"");

WriteLiteral(">\r\n");

            
            #line 125 "..\..\Views\Blog\Layout1\Search.cshtml"
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <img");

WriteAttribute("ng-src", Tuple.Create(" ng-src=\"", 6990), Tuple.Create("\"", 7014)
            
            #line 128 "..\..\Views\Blog\Layout1\Search.cshtml"
, Tuple.Create(Tuple.Create("", 6999), Tuple.Create<System.Object, System.Int32>(item.BlogImage
            
            #line default
            #line hidden
, 6999), false)
);

WriteLiteral(" class=\"img-responsive\"");

WriteLiteral(" onerror=\"this.src = DEFAULT_IMAGE_URL\"");

WriteLiteral(">\r\n");

            
            #line 129 "..\..\Views\Blog\Layout1\Search.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </div>\r\n                                    <" +
"div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n                                        <h6");

WriteLiteral(" class=\"blog-h6\"");

WriteLiteral(">");

            
            #line 132 "..\..\Views\Blog\Layout1\Search.cshtml"
                                                       Write(Model.BlogList.Results[0].Category);

            
            #line default
            #line hidden
WriteLiteral("</h6>\r\n                                        <h4");

WriteLiteral(" class=\"blog-h4\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 7391), Tuple.Create("\"", 7455)
            
            #line 133 "..\..\Views\Blog\Layout1\Search.cshtml"
, Tuple.Create(Tuple.Create("", 7398), Tuple.Create<System.Object, System.Int32>(Url.Action("blogdetail", "blog", new { url = @item.URL})
            
            #line default
            #line hidden
, 7398), false)
);

WriteLiteral(">");

            
            #line 133 "..\..\Views\Blog\Layout1\Search.cshtml"
                                                                                                                           Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</a></h4>\r\n                                        <p");

WriteLiteral(" class=\"blog-intro\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 135 "..\..\Views\Blog\Layout1\Search.cshtml"
                                       Write(item.Abstract);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </p>\r\n                                 " +
"       <p");

WriteLiteral(" class=\"blog-category\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 138 "..\..\Views\Blog\Layout1\Search.cshtml"
                                       Write(item.Days);

            
            #line default
            #line hidden
WriteLiteral(" days ago. By <a");

WriteAttribute("href", Tuple.Create(" href=\"", 7786), Tuple.Create("\"", 7810)
, Tuple.Create(Tuple.Create("", 7793), Tuple.Create("/", 7793), true)
            
            #line 138 "..\..\Views\Blog\Layout1\Search.cshtml"
, Tuple.Create(Tuple.Create("", 7794), Tuple.Create<System.Object, System.Int32>(item.EditorSlug
            
            #line default
            #line hidden
, 7794), false)
);

WriteLiteral(">");

            
            #line 138 "..\..\Views\Blog\Layout1\Search.cshtml"
                                                                                           Write(item.Author);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                        </p>\r\n                             " +
"       </div>\r\n                                </div>\r\n                         " +
"   </div>\r\n");

            
            #line 143 "..\..\Views\Blog\Layout1\Search.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n");

            
            #line 145 "..\..\Views\Blog\Layout1\Search.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n");

            
            #line 148 "..\..\Views\Blog\Layout1\Search.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral(" \r\n</section>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script>\r\n        window.app.constant(\'blogConfig\', {});\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
