#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Omnicx.WebStore;
    using Omnicx.WebStore.Core;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_LayoutError.cshtml")]
    public partial class _Views_Shared__LayoutError_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__LayoutError_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_LayoutError.cshtml"
  
/*
    Name: Error Layout
    Purpose: Show Error Messages
    Structure: /Views/Shared/_LayoutError.cshtml
    Contains (Partial Views Used):

    Contained In (Where we Use this View):
    */

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html >\r\n<head>\r\n    <title></title>\r\n");

WriteLiteral("    ");

            
            #line 15 "..\..\Views\Shared\_LayoutError.cshtml"
Write(Styles.Render("~/bundles/style-css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n<div>\r\n    <div");

WriteLiteral(" id=\"content\"");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 21 "..\..\Views\Shared\_LayoutError.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
