#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    
    #line 1 "..\..\Views\Shared\_LookbookLayout.cshtml"
    using Microsoft.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_LookbookLayout.cshtml"
    using Omnicx.API.SDK.Helpers;
    
    #line default
    #line hidden
    using Omnicx.WebStore;
    using Omnicx.WebStore.Core;
    
    #line 2 "..\..\Views\Shared\_LookbookLayout.cshtml"
    using Omnicx.WebStore.Core.Controllers;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\_LookbookLayout.cshtml"
    using Omnicx.WebStore.Models.Enums;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_LookbookLayout.cshtml")]
    public partial class _Views_Shared__LookbookLayout_cshtml : Omnicx.WebStore.Core.Services.Infrastructure.CustomBaseViewPage<dynamic>
    {
        public _Views_Shared__LookbookLayout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(" class=\"csstransforms csstransforms3d csstransitions\"");

WriteLiteral(" ng-app=\"btApp\"");

WriteLiteral(" ng-controller=\"globalCtrl as gm\"");

WriteLiteral(" id=\"sidebarFix\"");

WriteLiteral(">\r\n<head>\r\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Views\Shared\_LookbookLayout.cshtml"
Write(Html.Partial("~/Views/Shared/_LayoutHeadTag.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Views\Shared\_LookbookLayout.cshtml"
Write(Styles.Render("~/bundles/lookbook-css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body");

WriteLiteral(" class=\"pace-done\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Views\Shared\_LookbookLayout.cshtml"
Write(Html.GetGlobalSnipptes(SnippetPlacements.BodyStartHtmlTagAfter));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 14 "..\..\Views\Shared\_LookbookLayout.cshtml"
Write(RenderSection("siteheader", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <header");

WriteLiteral(" class=\"siteHeader\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("        ");

            
            #line 17 "..\..\Views\Shared\_LookbookLayout.cshtml"
   Write(Html.Partial("~/Views/Shared/_LayoutHeader.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral("></div>\r\n        <div>\r\n");

WriteLiteral("            ");

            
            #line 20 "..\..\Views\Shared\_LookbookLayout.cshtml"
       Write(Html.Partial("~/Views/Shared/_Alerts.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"pace  pace-inactive\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"pace-progress\"");

WriteLiteral(" data-progress-text=\"100%\"");

WriteLiteral(" data-progress=\"99\"");

WriteLiteral(" style=\"transform: translate3d(100%, 0px, 0px);\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pace-progress-inner\"");

WriteLiteral("></div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"pace-activity\"");

WriteLiteral("></div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(" id=\"all\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"main-content inner-top-xs\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 31 "..\..\Views\Shared\_LookbookLayout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 32 "..\..\Views\Shared\_LookbookLayout.cshtml"
           Write(Html.GetGlobalSnipptes(SnippetPlacements.PageContainerAfter));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

            
            #line 35 "..\..\Views\Shared\_LookbookLayout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Shared\_LookbookLayout.cshtml"
          /*Search popup for Mobile View*/
            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"modal fade in\"");

WriteLiteral(" id=\"globalSearch\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-dialog modal-xl\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"modal-header text-center\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" href=\"/\"");

WriteLiteral(">\r\n                            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1817), Tuple.Create("\"", 1863)
, Tuple.Create(Tuple.Create("", 1823), Tuple.Create<System.Object, System.Int32>(Href("~/assets/theme/ocx/images/logo-small.png")
, 1823), false)
);

WriteLiteral(" alt=\"OCX Store logo\"");

WriteLiteral(" style=\"margin-top: -10px; margin-left: 15px;\"");

WriteLiteral("><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">");

            
            #line 41 "..\..\Views\Shared\_LookbookLayout.cshtml"
                                                                                                                                                                    Write(LT("Header.Text.GoHome", "OCX Store - go to homepage"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        </a>\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close search-close-btn\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">×</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">");

            
            #line 43 "..\..\Views\Shared\_LookbookLayout.cshtml"
                                                                                                                                                    Write(LT("Checkout.Button.Close", "Close"));

            
            #line default
            #line hidden
WriteLiteral("</span></button>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"modal-body no-padding\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 47 "..\..\Views\Shared\_LookbookLayout.cshtml"
                       Write(Html.Partial("~/Views/Shared/_SearchBox.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral("></div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </header" +
">\r\n");

WriteLiteral("    ");

            
            #line 55 "..\..\Views\Shared\_LookbookLayout.cshtml"
Write(Html.Partial("~/Views/Shared/_LayoutFooter.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 56 "..\..\Views\Shared\_LookbookLayout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Shared\_LookbookLayout.cshtml"
      
        var pcaAccessCode = "";
        if (SessionContext.CurrentSiteConfig != null && SessionContext.CurrentSiteConfig.GeoLocators != null)
        {
            var pca = SessionContext.CurrentSiteConfig.GeoLocators.FirstOrDefault(x => x.PluginCode == Omnicx.WebStore.Models.Enums.GeoLocatorPlugin.PCA.ToString());
            if (pca != null)
            {
                pcaAccessCode = pca.AccessKey;
            }
        }

            
            #line default
            #line hidden
WriteLiteral("        <script>\r\n            var pcaAccessCode = \"");

            
            #line 67 "..\..\Views\Shared\_LookbookLayout.cshtml"
                            Write(pcaAccessCode);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        </script>\r\n");

            
            #line 69 "..\..\Views\Shared\_LookbookLayout.cshtml"
    
            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"dvloader\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"global-loader\"");

WriteLiteral(">\r\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3352), Tuple.Create("\"", 3394)
, Tuple.Create(Tuple.Create("", 3358), Tuple.Create<System.Object, System.Int32>(Href("~/assets/theme/ocx/images/loader.svg")
, 3358), false)
);

WriteLiteral(" />\r\n        </span>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"overlay\"");

WriteLiteral("></div>\r\n");

DefineSection("scripts", () => {

            
            #line 76 "..\..\Views\Shared\_LookbookLayout.cshtml"
    
            
            #line default
            #line hidden
});

WriteLiteral("    ");

            
            #line 77 "..\..\Views\Shared\_LookbookLayout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script>\r\n        var setContactForm = \'");

            
            #line 79 "..\..\Views\Shared\_LookbookLayout.cshtml"
                          Write(Html.BuildUrlFromExpression<CommonController>(c => c.ContactForm(null)));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var getBasketUrl = \'");

            
            #line 80 "..\..\Views\Shared\_LookbookLayout.cshtml"
                        Write(Html.BuildUrlFromExpression<BasketController>(c => c.GetBasketData()));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var addToBasket = \'");

            
            #line 81 "..\..\Views\Shared\_LookbookLayout.cshtml"
                       Write(Html.BuildUrlFromExpression<BasketController>(c => c.AddtoBasket(null)));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var signIn = \'");

            
            #line 82 "..\..\Views\Shared\_LookbookLayout.cshtml"
                  Write(Html.BuildUrlFromExpression<AccountController>(c => c.SignIn(null)));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var register = \'");

            
            #line 83 "..\..\Views\Shared\_LookbookLayout.cshtml"
                    Write(Html.BuildUrlFromExpression<AccountController>(c => c.Registration(null)));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var getShippingMethods = \'");

            
            #line 84 "..\..\Views\Shared\_LookbookLayout.cshtml"
                              Write(Html.BuildUrlFromExpression<BasketController>(c => c.GetShippingMethods("")));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var updateShipping = \'");

            
            #line 85 "..\..\Views\Shared\_LookbookLayout.cshtml"
                          Write(Html.BuildUrlFromExpression<BasketController>(c => c.UpdateShipping(null,null,null,null)));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var applyPromoCode = \'");

            
            #line 86 "..\..\Views\Shared\_LookbookLayout.cshtml"
                          Write(Html.BuildUrlFromExpression<BasketController>(c => c.ApplyPromoCode(null,null)));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var currencySettingUrl = \'");

            
            #line 87 "..\..\Views\Shared\_LookbookLayout.cshtml"
                              Write(Html.BuildUrlFromExpression<HomeController>(c => c.UpdateCurrencySetting(null)));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var paymentMethodsUrl = \'");

            
            #line 88 "..\..\Views\Shared\_LookbookLayout.cshtml"
                             Write(Html.BuildUrlFromExpression<CheckoutController>(c => c.GetPaymentMethods()));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var newsLetterSubscription = \'");

            
            #line 89 "..\..\Views\Shared\_LookbookLayout.cshtml"
                                  Write(Html.BuildUrlFromExpression<AccountController>(c => c.NewsletterSubscription(null)));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var removePromoCode = \'");

            
            #line 90 "..\..\Views\Shared\_LookbookLayout.cshtml"
                           Write(Html.BuildUrlFromExpression<BasketController>(c => c.RemovePromoCode("","")));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var forgotPassword = \'");

            
            #line 91 "..\..\Views\Shared\_LookbookLayout.cshtml"
                          Write(Html.BuildUrlFromExpression<AccountController>(c => c.ForgotPassword(null)));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var bulkAddproduct = \'");

            
            #line 92 "..\..\Views\Shared\_LookbookLayout.cshtml"
                          Write(Html.BuildUrlFromExpression<BasketController>(c=> c.BulkAddProduct(null)));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var companyRegisterUrl = \'");

            
            #line 93 "..\..\Views\Shared\_LookbookLayout.cshtml"
                              Write(Html.BuildUrlFromExpression<B2BController>(c => c.CreateRequest(null)));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var getDefaultCountryUrl = \'");

            
            #line 94 "..\..\Views\Shared\_LookbookLayout.cshtml"
                                Write(Html.BuildUrlFromExpression<AccountController>(c => c.GetDefaultCountry()));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var removeWishList = \'");

            
            #line 95 "..\..\Views\Shared\_LookbookLayout.cshtml"
                          Write(Html.BuildUrlFromExpression<CheckoutController>(c => c.RemoveWishList("",false)));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n          var languageSettingUrl = \'");

            
            #line 96 "..\..\Views\Shared\_LookbookLayout.cshtml"
                                Write(Html.BuildUrlFromExpression<HomeController>(c => c.UpdateLanCultureSetting(null)));

            
            #line default
            #line hidden
WriteLiteral(@"';
        window.app.constant('globalConfig', {
            setContactForm: setContactForm,
            getBasketUrl: getBasketUrl,
            addToBasket: addToBasket,
            signIn: signIn,
            register: register,
            getShippingMethods: getShippingMethods,
            updateShipping: updateShipping,
            applyPromoCode: applyPromoCode,
            currencySettingUrl: currencySettingUrl,
            paymentMethodsUrl: paymentMethodsUrl,
            newsLetterSubscription: newsLetterSubscription,
            removePromoCode: removePromoCode,
            forgotPassword: forgotPassword,
            bulkAddproduct: bulkAddproduct,
            companyRegisterUrl: companyRegisterUrl,
            pcaAccessCode: pcaAccessCode,
            getDefaultCountryUrl: getDefaultCountryUrl,
            removeWishList: removeWishList,
            languageSettingUrl: languageSettingUrl
        });
    </script>
");

WriteLiteral("    ");

            
            #line 119 "..\..\Views\Shared\_LookbookLayout.cshtml"
Write(Html.GetGlobalSnipptes(SnippetPlacements.BodyEndHtmlTagBefore));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 120 "..\..\Views\Shared\_LookbookLayout.cshtml"
Write(Scripts.Render("~/bundles/lookbook-js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
