#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Omnicx.WebStore;
    using Omnicx.WebStore.Core;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_MobileMenu.cshtml")]
    public partial class _Views_Shared__MobileMenu_cshtml : Omnicx.WebStore.Core.Services.Infrastructure.CustomBaseViewPage<Omnicx.WebStore.Models.Site.NavigationModel>
    {
        public _Views_Shared__MobileMenu_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_MobileMenu.cshtml"
  
/*
    Name: Mobile Menu
    Purpose: Mobile Menu UI
    Structure: /Views/Shared/_MobileMenu.cshtml
    Contains (Partial Views Used):

    Contained In (Where we Use this View):
        a-/Views/Shared/_MobileHeaderLayout.cshtml
    */

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 14 "..\..\Views\Shared\_MobileMenu.cshtml"
  /*Start Mobile Mega Menu UI*/
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row demo-1 visible-xs\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"main clearfix\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"column\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"dl-menu\"");

WriteLiteral(" class=\"dl-menuwrapper\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"dl-trigger\"");

WriteLiteral(" id=\"openMenu\"");

WriteLiteral("><span");

WriteLiteral(" class=\"label-0\"");

WriteLiteral(">Menu</span><span></span><span></span><span></span><span></span><span></span></bu" +
"tton>\r\n\r\n");

            
            #line 22 "..\..\Views\Shared\_MobileMenu.cshtml"
                
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Shared\_MobileMenu.cshtml"
                   if (Model != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <ul");

WriteLiteral(" class=\"dl-menu\"");

WriteLiteral(">\r\n                            <li>\r\n                                <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 no-padding\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-xs-3 menuAccount no-padding\"");

WriteLiteral(">\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1080), Tuple.Create("\"", 1119)
            
            #line 28 "..\..\Views\Shared\_MobileMenu.cshtml"
, Tuple.Create(Tuple.Create("", 1087), Tuple.Create<System.Object, System.Int32>(Url.Action("SignIn", "Account")
            
            #line default
            #line hidden
, 1087), false)
);

WriteLiteral(">\r\n                                            <i");

WriteLiteral(" class=\"sprite sprite-browsers-customer\"");

WriteLiteral("></i>                                           \r\n                               " +
"             <span>My Account</span>\r\n                                        </" +
"a>\r\n                                    </div>\r\n                                " +
"    <div");

WriteLiteral(" class=\"col-xs-3 menuAccount no-padding\"");

WriteLiteral(">\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1543), Tuple.Create("\"", 1584)
            
            #line 34 "..\..\Views\Shared\_MobileMenu.cshtml"
, Tuple.Create(Tuple.Create("", 1550), Tuple.Create<System.Object, System.Int32>(Url.Action("Wishlist", "Account")
            
            #line default
            #line hidden
, 1550), false)
);

WriteLiteral(">\r\n                                            <i");

WriteLiteral(" class=\"sprite sprite-browsers-wishlist\"");

WriteLiteral("></i>                                            \r\n                              " +
"              <span>Wishlist</span>\r\n                                        </a" +
">\r\n                                    </div>\r\n                                 " +
"   <div");

WriteLiteral(" class=\"col-xs-3 menuAccount no-padding\"");

WriteLiteral(">\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2007), Tuple.Create("\"", 2052)
            
            #line 40 "..\..\Views\Shared\_MobileMenu.cshtml"
, Tuple.Create(Tuple.Create("", 2014), Tuple.Create<System.Object, System.Int32>(Url.Action("OrderHistory", "Account")
            
            #line default
            #line hidden
, 2014), false)
);

WriteLiteral(">\r\n                                            <i");

WriteLiteral(" class=\"sprite sprite-browsers-order\"");

WriteLiteral("></i>                                            \r\n                              " +
"              <span>My Orders</span>\r\n                                        </" +
"a>\r\n                                    </div>\r\n                                " +
"    <div");

WriteLiteral(" class=\"col-xs-3 menuAccount no-padding\"");

WriteLiteral(">\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2473), Tuple.Create("\"", 2512)
            
            #line 46 "..\..\Views\Shared\_MobileMenu.cshtml"
, Tuple.Create(Tuple.Create("", 2480), Tuple.Create<System.Object, System.Int32>(Url.Action("Logout", "Account")
            
            #line default
            #line hidden
, 2480), false)
);

WriteLiteral(">\r\n                                            <i");

WriteLiteral(" class=\"sprite sprite-browsers-logout\"");

WriteLiteral(@"></i>                                            
                                            <span>Logout</span>
                                        </a>
                                    </div>
                                </div>
                            </li>
");

            
            #line 53 "..\..\Views\Shared\_MobileMenu.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Shared\_MobileMenu.cshtml"
                             foreach (var items in @Model.Header.OrderBy(o => o.DisplayOrder))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3084), Tuple.Create("\"", 3108)
, Tuple.Create(Tuple.Create("", 3091), Tuple.Create("/", 3091), true)
            
            #line 56 "..\..\Views\Shared\_MobileMenu.cshtml"
, Tuple.Create(Tuple.Create("", 3092), Tuple.Create<System.Object, System.Int32>(items.Hyperlink
            
            #line default
            #line hidden
, 3092), false)
);

WriteLiteral(">");

            
            #line 56 "..\..\Views\Shared\_MobileMenu.cshtml"
                                                           Write(items.Caption);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\r\n");

            
            #line 58 "..\..\Views\Shared\_MobileMenu.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\Shared\_MobileMenu.cshtml"
                                      
                                        if (items.NavBlocks != null && items.NavBlocks.Count > 0)
                                        {


            
            #line default
            #line hidden
WriteLiteral("                                            <ul");

WriteLiteral(" class=\"dl-submenu\"");

WriteLiteral(">\r\n");

            
            #line 63 "..\..\Views\Shared\_MobileMenu.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\Shared\_MobileMenu.cshtml"
                                                 foreach (var child1 in @items.NavBlocks.OrderBy(o => o.DisplayOrder))
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <li>\r\n                       " +
"                                 <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 66 "..\..\Views\Shared\_MobileMenu.cshtml"
                                                               Write(child1.BoxTitle);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                                        <ul");

WriteLiteral(" class=\"dl-submenu\"");

WriteLiteral(">\r\n");

            
            #line 68 "..\..\Views\Shared\_MobileMenu.cshtml"
                                                            
            
            #line default
            #line hidden
            
            #line 68 "..\..\Views\Shared\_MobileMenu.cshtml"
                                                             foreach (var child2 in @child1.NavItems)
                                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                                <li>\r\n           " +
"                                                         <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4091), Tuple.Create("\"", 4115)
, Tuple.Create(Tuple.Create("", 4098), Tuple.Create("/", 4098), true)
            
            #line 71 "..\..\Views\Shared\_MobileMenu.cshtml"
, Tuple.Create(Tuple.Create("", 4099), Tuple.Create<System.Object, System.Int32>(child2.ItemLink
            
            #line default
            #line hidden
, 4099), false)
);

WriteLiteral("> ");

            
            #line 71 "..\..\Views\Shared\_MobileMenu.cshtml"
                                                                                            Write(child2.Caption);

            
            #line default
            #line hidden
WriteLiteral(" </a>\r\n                                                                </li>\r\n");

            
            #line 73 "..\..\Views\Shared\_MobileMenu.cshtml"
                                                            }

            
            #line default
            #line hidden
WriteLiteral("                                                            <li>\r\n               " +
"                                                 <span");

WriteLiteral(" class=\"megamenu-img\"");

WriteLiteral(">");

            
            #line 75 "..\..\Views\Shared\_MobileMenu.cshtml"
                                                                                      Write(Html.Raw(child1.ContentBody));

            
            #line default
            #line hidden
WriteLiteral(@"</span>
                                                            </li>                                                            
                                                        </ul>
                                                    </li>
");

            
            #line 79 "..\..\Views\Shared\_MobileMenu.cshtml"
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                                <li>\r\n                           " +
"                         <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4877), Tuple.Create("\"", 4901)
, Tuple.Create(Tuple.Create("", 4884), Tuple.Create("/", 4884), true)
            
            #line 81 "..\..\Views\Shared\_MobileMenu.cshtml"
, Tuple.Create(Tuple.Create("", 4885), Tuple.Create<System.Object, System.Int32>(items.Hyperlink
            
            #line default
            #line hidden
, 4885), false)
);

WriteLiteral(">");

            
            #line 81 "..\..\Views\Shared\_MobileMenu.cshtml"
                                                                           Write(items.Caption);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                                </li>\r\n                    " +
"                        </ul>\r\n");

            
            #line 84 "..\..\Views\Shared\_MobileMenu.cshtml"
                                        }
                                    
            
            #line default
            #line hidden
WriteLiteral("\r\n                                </li>\r\n");

            
            #line 87 "..\..\Views\Shared\_MobileMenu.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                            <li>\r\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5261), Tuple.Create("\"", 5301)
            
            #line 89 "..\..\Views\Shared\_MobileMenu.cshtml"
, Tuple.Create(Tuple.Create("", 5268), Tuple.Create<System.Object, System.Int32>(Url.Action("BrandList", "Brand")
            
            #line default
            #line hidden
, 5268), false)
);

WriteLiteral(">");

            
            #line 89 "..\..\Views\Shared\_MobileMenu.cshtml"
                                                                       Write(LT("Header.Nav.Brands", "Brands"));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                            </li>\r\n                            <li>\r\n      " +
"                          <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5446), Tuple.Create("\"", 5481)
            
            #line 92 "..\..\Views\Shared\_MobileMenu.cshtml"
, Tuple.Create(Tuple.Create("", 5453), Tuple.Create<System.Object, System.Int32>(Url.Action("blogs", "blog")
            
            #line default
            #line hidden
, 5453), false)
);

WriteLiteral(" class=\"link1\"");

WriteLiteral(">");

            
            #line 92 "..\..\Views\Shared\_MobileMenu.cshtml"
                                                                                Write(LT("Header.Nav.Blogs", "Blogs"));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\r\n                            </li>\r\n                        </ul>\r\n");

            
            #line 96 "..\..\Views\Shared\_MobileMenu.cshtml"
                                        }
                
            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

            
            #line 103 "..\..\Views\Shared\_MobileMenu.cshtml"
  /*End Mobile MEga Menu*/
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
