#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Omnicx.WebStore;
    using Omnicx.WebStore.Core;
    
    #line 13 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
    using Omnicx.WebStore.Core.Helpers;
    
    #line default
    #line hidden
    
    #line 14 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
    using Omnicx.WebStore.Framework.Helpers;
    
    #line default
    #line hidden
    
    #line 12 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
    using Omnicx.WebStore.Models.Enums;
    
    #line default
    #line hidden
    
    #line 15 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
    using Omnicx.WebStore.Models.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Checkout/_HotelShippingAddress.cshtml")]
    public partial class _Views_Checkout__HotelShippingAddress_cshtml : Omnicx.WebStore.Core.Services.Infrastructure.CustomBaseViewPage<Omnicx.WebStore.Models.Commerce.AddressModel>
    {
        public _Views_Checkout__HotelShippingAddress_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
  
/*
    Name: Shipping Address
    Purpose: Shipping Address Form
    Structure: /Views/Checkout/_ShippingAddress.cshtml
    Contains (Partial Views Used):

    Contained In (Where we Use this View):
        a-/Views/Checkout/OnePageCheckout.cshtml
    */

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 17 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
  
    var addressForm = Html.Angular().ModelFor("ck.model.checkout.shippingAddress");
    var userRole = SessionContext.CurrentUserRole;

            
            #line default
            #line hidden
WriteLiteral("\r\n<form");

WriteLiteral(" name=\"shippingForm\"");

WriteLiteral(" role=\"form\"");

WriteAttribute("ng-show", Tuple.Create(" ng-show=\"", 729), Tuple.Create("\"", 822)
, Tuple.Create(Tuple.Create("", 739), Tuple.Create("ck.model.checkout.selectedShipping.type", 739), true)
, Tuple.Create(Tuple.Create(" ", 778), Tuple.Create("==", 779), true)
, Tuple.Create(Tuple.Create(" ", 781), Tuple.Create("\'", 782), true)
            
            #line 21 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
            , Tuple.Create(Tuple.Create("", 783), Tuple.Create<System.Object, System.Int32>(ShippingMethodTypes.Pickup.ToString()
            
            #line default
            #line hidden
, 783), false)
, Tuple.Create(Tuple.Create("", 821), Tuple.Create("\'", 821), true)
);

WriteLiteral(" novalidate>\r\n    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(" ng-hide=\"ck.hideShippingAddress\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12 wzc--heading--pannel border-bottom\"");

WriteLiteral(">\r\n                <h5");

WriteLiteral(" class=\"wzc--h5\"");

WriteLiteral(">");

            
            #line 25 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
                               Write(LT("Checkout.Label.DeliveryAddress", "Delivery Address"));

            
            #line default
            #line hidden
WriteLiteral("</h5>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row wzc--address--border\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row margin-top-md\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-6 col-md-4 col-lg-4\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" ng-class=\"vm.getValidationClass()\"");

WriteLiteral(" form-group-validation=\"Title\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"Title\"");

WriteLiteral(" class=\"control-label ng-scope\"");

WriteLiteral(">");

            
            #line 33 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
                                                                         Write(LT("MyAccount.Text.Title", "Title"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                            <select");

WriteLiteral(" name=\"Title\"");

WriteLiteral(" tabindex=\"1\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-label=\"Title\"");

WriteLiteral(" ng-model=\"ck.model.checkout.shippingAddress.title\"");

WriteLiteral(" ");

WriteLiteral(">\r\n                                <option");

WriteLiteral(" ng-selected=\"ck.model.checkout.shippingAddress.title == null\"");

WriteLiteral(" value=\"\"");

WriteLiteral(">");

            
            #line 35 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
                                                                                                          Write(LT("MyAccount.Text.Title", "Title"));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                                <option");

WriteLiteral(" value=\"Miss\"");

WriteLiteral(">Miss</option>\r\n                                <option");

WriteLiteral(" value=\"Mr\"");

WriteLiteral(">Mr</option>\r\n                                <option");

WriteLiteral(" value=\"Mrs\"");

WriteLiteral(">Mrs</option>\r\n                            </select>\r\n                        </d" +
"iv>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n   " +
"         <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 47 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
                   Write(addressForm.FormGroupFor(x => x.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 52 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
                   Write(addressForm.FormGroupFor(x => x.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
"     <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 59 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
                   Write(addressForm.FormGroupFor(x => x.Address1));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 64 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
                   Write(addressForm.FormGroupFor(x => x.Address2));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
"     <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-6 col-md-3\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 71 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
                   Write(addressForm.FormGroupFor(x => x.City));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-6 col-md-3\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 76 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
                   Write(addressForm.FormGroupFor(x => x.PostCode));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-6 col-md-3\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 81 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
                   Write(addressForm.FormGroupFor(x => x.State));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 86 "..\..\Views\Checkout\_HotelShippingAddress.cshtml"
                   Write(addressForm.FormGroupFor(x => x.PhoneNo));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
" </div>\r\n    </div>\r\n</form>");

        }
    }
}
#pragma warning restore 1591
