#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Omnicx.WebStore;
    using Omnicx.WebStore.Core;
    
    #line 13 "..\..\Views\Checkout\_OrderSummary.cshtml"
    using Omnicx.WebStore.Models.Enums;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Checkout/_OrderSummary.cshtml")]
    public partial class _Views_Checkout__OrderSummary_cshtml : Omnicx.WebStore.Core.Services.Infrastructure.CustomBaseViewPage<dynamic>
    {
        public _Views_Checkout__OrderSummary_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Checkout\_OrderSummary.cshtml"
  
    /*
        Name: Order Summery
        Purpose: Contains Order item Lines, Promotion panel and Order Amount Information
        Structure: /Views/Checkout/_OrderSummary.cshtml
        Contains (Partial Views Used):

        Contained In (Where we Use this View):
            a-/Views/Basket/OnePageCheckout.cshtml
        */
    var giftOrder = Convert.ToInt16(SessionContext.CurrentSiteConfig.BasketSettings.EnableIsGiftORMe);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"summery-box\"");

WriteLiteral(" id=\"order-summary\"");

WriteLiteral(" ng-contr>\r\n    <div ng-cloak");

WriteLiteral(" class=\"alert alert-danger wishdiv\"");

WriteLiteral(" ng-show=\"ck.wishlisterror\"");

WriteLiteral(">\r\n        User <strong>");

            
            #line 17 "..\..\Views\Checkout\_OrderSummary.cshtml"
                Write(LT("ProductDetail.Message.LoginRequired", "Login Required"));

            
            #line default
            #line hidden
WriteLiteral("!</strong>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral(">\r\n        <h3> ");

            
            #line 20 "..\..\Views\Checkout\_OrderSummary.cshtml"
        Write(LT("Checkout.Label.PriceDetails", "Price Details"));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n    </div>    \r\n    <p");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" class=\"text-muted padding-sm label-span-desc\"");

WriteLiteral(">");

            
            #line 22 "..\..\Views\Checkout\_OrderSummary.cshtml"
                                                                   Write(LT("Checkout.Text.ShippingInfo", "Shipping and additional costs are calculated based on the values you have entered"));

            
            #line default
            #line hidden
WriteLiteral(".</p>\r\n\r\n    <div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"table no-margin-top\"");

WriteLiteral(">\r\n            <tbody>\r\n                <tr>\r\n                    <td>");

            
            #line 28 "..\..\Views\Checkout\_OrderSummary.cshtml"
                   Write(LT("Checkout.Label.Subtotal", "Subtotal"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <th");

WriteLiteral(" ng-bind=\"ck.basket.subTotal.formatted.withTax\"");

WriteLiteral(" class=\"text-right\"");

WriteLiteral("></th>\r\n                </tr>\r\n                <tr>\r\n                    <td>");

            
            #line 32 "..\..\Views\Checkout\_OrderSummary.cshtml"
                   Write(LT("Checkout.Label.ShippingCharge", "Shipping and handling"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <th");

WriteLiteral(" ng-bind=\"ck.basket.shippingCharge.formatted.withTax\"");

WriteLiteral(" class=\"text-right\"");

WriteLiteral("></th>\r\n                </tr>\r\n                ");

WriteLiteral("\r\n                <tr>\r\n                    <td>");

            
            #line 40 "..\..\Views\Checkout\_OrderSummary.cshtml"
                   Write(LT("Checkout.Label.Discount", "Discount"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <th");

WriteLiteral(" ng-bind=\"ck.basket.discount.formatted.withTax\"");

WriteLiteral(" class=\"text-right\"");

WriteLiteral("></th>\r\n                </tr>\r\n                <tr");

WriteLiteral(" ng-show=\"ck.basket.promotionsApplied.length>0\"");

WriteLiteral(" id=\"promoApplied4\"");

WriteLiteral(">\r\n                    <td>Promotions Applied:</td>\r\n                    <th");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n                        <ul");

WriteLiteral(" class=\"promo-ul\"");

WriteLiteral(">\r\n                            <li");

WriteLiteral(" class=\"no-padding\"");

WriteLiteral(" ng-repeat=\"promotion in ck.basket.promotionsApplied\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" class=\"\"");

WriteLiteral(" title=\"Remove\"");

WriteLiteral(" ng-click=\"ck.removePromoCode(ck.basket.id,promotion.promoCode)\"");

WriteLiteral("><span");

WriteLiteral(" ng-bind=\"promotion.name\"");

WriteLiteral("></span> <i");

WriteLiteral(" class=\"fa fa-remove\"");

WriteLiteral("></i></a>\r\n                            </li>\r\n                        </ul>\r\n    " +
"                </th>\r\n                </tr>\r\n                <tr");

WriteLiteral(" class=\"total\"");

WriteLiteral(">\r\n                    <td>");

            
            #line 54 "..\..\Views\Checkout\_OrderSummary.cshtml"
                   Write(LT("Checkout.Label.OrderTotal", "Amount Payable"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <th");

WriteLiteral(" ng-bind=\"ck.basket.grandTotal.formatted.withTax\"");

WriteLiteral(" class=\"text-right\"");

WriteLiteral("></th>\r\n                </tr>\r\n                <tr>\r\n                    <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(" class=\"sml-text\"");

WriteLiteral(" ng-cloak");

WriteAttribute("ng-bind", Tuple.Create(" ng-bind=\"", 3095), Tuple.Create("\"", 3196)
, Tuple.Create(Tuple.Create("", 3105), Tuple.Create("\'", 3105), true)
            
            #line 58 "..\..\Views\Checkout\_OrderSummary.cshtml"
, Tuple.Create(Tuple.Create("", 3106), Tuple.Create<System.Object, System.Int32>(LT("YourBag.Text.IncludingVATof", "including VAT of")
            
            #line default
            #line hidden
, 3106), false)
, Tuple.Create(Tuple.Create("", 3160), Tuple.Create("\'+ck.basket.grandTotal.formatted.tax", 3160), true)
);

WriteLiteral("></td                    \r\n                </tr>\r\n                <tr");

WriteLiteral(" class=\"total\"");

WriteLiteral(" ng-show=\"ck.showRemainingAmount\"");

WriteLiteral(">\r\n                    <td>");

            
            #line 61 "..\..\Views\Checkout\_OrderSummary.cshtml"
                   Write(LT("Checkout.Label.RemainingAmount", "Remaining Amount"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <th");

WriteLiteral(" ng-bind=\"ck.model.checkout.balanceAmount.formatted.withTax\"");

WriteLiteral(" class=\"text-right\"");

WriteLiteral("> </th>\r\n                    ");

WriteLiteral("\r\n                </tr>\r\n            </tbody>\r\n        </table>\r\n    </div>\r\n</di" +
"v>\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" ng-if=\"ck.model.checkout.basket.hasSubscription\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"summery-box\"");

WriteLiteral(" id=\"order-summary\"");

WriteLiteral(" ng-show=\"true\"");

WriteLiteral(">\r\n        <div ng-cloak");

WriteLiteral(" class=\"alert alert-danger wishdiv\"");

WriteLiteral(" ng-show=\"ck.wishlisterror\"");

WriteLiteral(">\r\n            User <strong>");

            
            #line 73 "..\..\Views\Checkout\_OrderSummary.cshtml"
                    Write(LT("ProductDetail.Message.LoginRequired", "Login Required"));

            
            #line default
            #line hidden
WriteLiteral("!</strong>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral(">\r\n            <h3> ");

            
            #line 76 "..\..\Views\Checkout\_OrderSummary.cshtml"
            Write(LT("Checkout.Label.PriceDetails", "Subscription Details"));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" class=\"table no-margin-top\"");

WriteLiteral(">\r\n                <tbody>\r\n                    <tr>\r\n                        <td" +
">");

            
            #line 83 "..\..\Views\Checkout\_OrderSummary.cshtml"
                       Write(LT("Checkout.Label.Subtotal", "Pricing Type"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <th");

WriteLiteral(" ng-bind=\"ck.subscriptionModel.selectedPricing\"");

WriteLiteral(" class=\"text-right\"");

WriteLiteral("></th>\r\n                    </tr>\r\n                    <tr>\r\n                    " +
"    <td>");

            
            #line 87 "..\..\Views\Checkout\_OrderSummary.cshtml"
                       Write(LT("Checkout.Label.Subtotal", "Subscription Fee"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <th");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n                            <span");

WriteAttribute("ng-if", Tuple.Create(" ng-if=\"", 4745), Tuple.Create("\"", 4834)
, Tuple.Create(Tuple.Create("", 4753), Tuple.Create("ck.subscriptionPlan.PricingType", 4753), true)
, Tuple.Create(Tuple.Create(" ", 4784), Tuple.Create("==", 4785), true)
, Tuple.Create(Tuple.Create(" ", 4787), Tuple.Create("\'", 4788), true)
            
            #line 89 "..\..\Views\Checkout\_OrderSummary.cshtml"
, Tuple.Create(Tuple.Create("", 4789), Tuple.Create<System.Object, System.Int32>(SubscriptionPricingTypes.Flat.GetHashCode()
            
            #line default
            #line hidden
, 4789), false)
, Tuple.Create(Tuple.Create("", 4833), Tuple.Create("\'", 4833), true)
);

WriteLiteral(">\r\n                                <span");

WriteAttribute("ng-if", Tuple.Create(" ng-if=\"", 4875), Tuple.Create("\"", 4960)
, Tuple.Create(Tuple.Create("", 4883), Tuple.Create("ck.subscriptionModel.selectedPricing", 4883), true)
, Tuple.Create(Tuple.Create(" ", 4919), Tuple.Create("==", 4920), true)
, Tuple.Create(Tuple.Create(" ", 4922), Tuple.Create("\'", 4923), true)
            
            #line 90 "..\..\Views\Checkout\_OrderSummary.cshtml"
      , Tuple.Create(Tuple.Create("", 4924), Tuple.Create<System.Object, System.Int32>(UserPricingType.OneTime.ToString()
            
            #line default
            #line hidden
, 4924), false)
, Tuple.Create(Tuple.Create("", 4959), Tuple.Create("\'", 4959), true)
);

WriteLiteral(" ng-bind=\"ck.subscriptionPlan.OneTimeFee.Formatted.WithTax\"");

WriteLiteral("></span>\r\n                                <span");

WriteAttribute("ng-if", Tuple.Create(" ng-if=\"", 5067), Tuple.Create("\"", 5154)
, Tuple.Create(Tuple.Create("", 5075), Tuple.Create("ck.subscriptionModel.selectedPricing", 5075), true)
, Tuple.Create(Tuple.Create(" ", 5111), Tuple.Create("==", 5112), true)
, Tuple.Create(Tuple.Create(" ", 5114), Tuple.Create("\'", 5115), true)
            
            #line 91 "..\..\Views\Checkout\_OrderSummary.cshtml"
      , Tuple.Create(Tuple.Create("", 5116), Tuple.Create<System.Object, System.Int32>(UserPricingType.Recurring.ToString()
            
            #line default
            #line hidden
, 5116), false)
, Tuple.Create(Tuple.Create("", 5153), Tuple.Create("\'", 5153), true)
);

WriteLiteral(" ng-bind=\"ck.subscriptionPlan.RecurringFee.Formatted.WithTax\"");

WriteLiteral("></span>\r\n                            </span>\r\n                            <span");

WriteAttribute("ng-if", Tuple.Create(" ng-if=\"", 5296), Tuple.Create("\"", 5385)
, Tuple.Create(Tuple.Create("", 5304), Tuple.Create("ck.subscriptionPlan.PricingType", 5304), true)
, Tuple.Create(Tuple.Create(" ", 5335), Tuple.Create("==", 5336), true)
, Tuple.Create(Tuple.Create(" ", 5338), Tuple.Create("\'", 5339), true)
            
            #line 93 "..\..\Views\Checkout\_OrderSummary.cshtml"
, Tuple.Create(Tuple.Create("", 5340), Tuple.Create<System.Object, System.Int32>(SubscriptionPricingTypes.Term.GetHashCode()
            
            #line default
            #line hidden
, 5340), false)
, Tuple.Create(Tuple.Create("", 5384), Tuple.Create("\'", 5384), true)
);

WriteLiteral(">\r\n                                <span");

WriteAttribute("ng-if", Tuple.Create(" ng-if=\"", 5426), Tuple.Create("\"", 5511)
, Tuple.Create(Tuple.Create("", 5434), Tuple.Create("ck.subscriptionModel.selectedPricing", 5434), true)
, Tuple.Create(Tuple.Create(" ", 5470), Tuple.Create("==", 5471), true)
, Tuple.Create(Tuple.Create(" ", 5473), Tuple.Create("\'", 5474), true)
            
            #line 94 "..\..\Views\Checkout\_OrderSummary.cshtml"
      , Tuple.Create(Tuple.Create("", 5475), Tuple.Create<System.Object, System.Int32>(UserPricingType.OneTime.ToString()
            
            #line default
            #line hidden
, 5475), false)
, Tuple.Create(Tuple.Create("", 5510), Tuple.Create("\'", 5510), true)
);

WriteLiteral(" ng-bind=\"ck.subscriptionModel.selectedTerm.OneTimeFee.Formatted.WithTax\"");

WriteLiteral("></span>\r\n                                <span");

WriteAttribute("ng-if", Tuple.Create(" ng-if=\"", 5632), Tuple.Create("\"", 5719)
, Tuple.Create(Tuple.Create("", 5640), Tuple.Create("ck.subscriptionModel.selectedPricing", 5640), true)
, Tuple.Create(Tuple.Create(" ", 5676), Tuple.Create("==", 5677), true)
, Tuple.Create(Tuple.Create(" ", 5679), Tuple.Create("\'", 5680), true)
            
            #line 95 "..\..\Views\Checkout\_OrderSummary.cshtml"
      , Tuple.Create(Tuple.Create("", 5681), Tuple.Create<System.Object, System.Int32>(UserPricingType.Recurring.ToString()
            
            #line default
            #line hidden
, 5681), false)
, Tuple.Create(Tuple.Create("", 5718), Tuple.Create("\'", 5718), true)
);

WriteLiteral(" ng-bind=\"ck.subscriptionModel.selectedTerm.RecurringFee.Formatted.WithTax\"");

WriteLiteral("></span>\r\n                            </span>\r\n                        </th>\r\n   " +
"                 </tr>\r\n                    <tr>\r\n                        <td>");

            
            #line 100 "..\..\Views\Checkout\_OrderSummary.cshtml"
                       Write(LT("Checkout.Label.Subtotal", "Sign Up Fee"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <th");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n                            <span");

WriteAttribute("ng-if", Tuple.Create(" ng-if=\"", 6088), Tuple.Create("\"", 6177)
, Tuple.Create(Tuple.Create("", 6096), Tuple.Create("ck.subscriptionPlan.PricingType", 6096), true)
, Tuple.Create(Tuple.Create(" ", 6127), Tuple.Create("==", 6128), true)
, Tuple.Create(Tuple.Create(" ", 6130), Tuple.Create("\'", 6131), true)
            
            #line 102 "..\..\Views\Checkout\_OrderSummary.cshtml"
, Tuple.Create(Tuple.Create("", 6132), Tuple.Create<System.Object, System.Int32>(SubscriptionPricingTypes.Flat.GetHashCode()
            
            #line default
            #line hidden
, 6132), false)
, Tuple.Create(Tuple.Create("", 6176), Tuple.Create("\'", 6176), true)
);

WriteLiteral(" ng-bind=\"ck.subscriptionPlan.SignUpFee.Formatted.WithTax\"");

WriteLiteral("></span>\r\n                            <span");

WriteAttribute("ng-if", Tuple.Create(" ng-if=\"", 6279), Tuple.Create("\"", 6368)
, Tuple.Create(Tuple.Create("", 6287), Tuple.Create("ck.subscriptionPlan.PricingType", 6287), true)
, Tuple.Create(Tuple.Create(" ", 6318), Tuple.Create("==", 6319), true)
, Tuple.Create(Tuple.Create(" ", 6321), Tuple.Create("\'", 6322), true)
            
            #line 103 "..\..\Views\Checkout\_OrderSummary.cshtml"
, Tuple.Create(Tuple.Create("", 6323), Tuple.Create<System.Object, System.Int32>(SubscriptionPricingTypes.Term.GetHashCode()
            
            #line default
            #line hidden
, 6323), false)
, Tuple.Create(Tuple.Create("", 6367), Tuple.Create("\'", 6367), true)
);

WriteLiteral(" ng-bind=\"ck.subscriptionModel.selectedTerm.SignUpFee.Formatted.WithTax\"");

WriteLiteral("></span>\r\n                        </th>\r\n                    </tr>\r\n             " +
"       <tr>\r\n                        <td>");

            
            #line 107 "..\..\Views\Checkout\_OrderSummary.cshtml"
                       Write(LT("Checkout.Label.Subtotal", "Sub Total"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <th");

WriteLiteral(" ng-bind=\"ck.basket.subscriptionTotal.formatted.withTax\"");

WriteLiteral(" class=\"text-right\"");

WriteLiteral("></th>\r\n                    </tr>\r\n                    <tr");

WriteLiteral(" class=\"total\"");

WriteLiteral(">\r\n                        <td>");

            
            #line 111 "..\..\Views\Checkout\_OrderSummary.cshtml"
                       Write(LT("Checkout.Label.OrderTotal", "Subscription Total"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <th");

WriteLiteral(" ng-bind=\"ck.basket.subscriptionTotal.formatted.withTax\"");

WriteLiteral(" class=\"text-right\"");

WriteLiteral("></th>\r\n                    </tr>\r\n                </tbody>\r\n            </table>" +
"\r\n        </div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"summery-box\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral(">\r\n        <h4><i");

WriteLiteral(" class=\"fa fa-ticket\"");

WriteLiteral("></i> ");

            
            #line 121 "..\..\Views\Checkout\_OrderSummary.cshtml"
                                    Write(LT("Checkout.Label.PromotionCode", "Coupon code"));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n    </div>\r\n    <p");

WriteLiteral(" class=\"text-muted padding-sm label-span-desc\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">");

            
            #line 123 "..\..\Views\Checkout\_OrderSummary.cshtml"
                                                                   Write(LT("Checkout.Text.HaveCoupon", "If you have a coupon code, please enter it in the box below"));

            
            #line default
            #line hidden
WriteLiteral(".</p>\r\n    <form");

WriteLiteral(" ng-submit=\"ck.applyPromoCode(ck.basket.id,promoCode)\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"input-group padding-sm\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"promoCode\"");

WriteLiteral(" placeholder=\"Enter Coupon Code\"");

WriteLiteral(" />\r\n            <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-orange\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-gift\"");

WriteLiteral("></i></button>\r\n            </span>\r\n        </div>\r\n        <!-- /input-group --" +
">\r\n    </form>\r\n    <div ng-cloak");

WriteLiteral(" class=\"alert alert-danger promo\"");

WriteLiteral(" ng-show=\"ck.invalidpromo\"");

WriteLiteral(">\r\n        <span>");

            
            #line 134 "..\..\Views\Checkout\_OrderSummary.cshtml"
         Write(LT("Checkout.Text.InValidPromoMessage", "PromoCode Invalid!"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    </div>\r\n    <div ng-cloak");

WriteLiteral(" class=\"alert alert-success promovalid\"");

WriteLiteral(" ng-show=\"ck.validpromo\"");

WriteLiteral(">\r\n        <span>");

            
            #line 137 "..\..\Views\Checkout\_OrderSummary.cshtml"
         Write(LT("Checkout.Text.ValidPromoMessage", "Successfully Applied"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    </div>\r\n    <div ng-cloak");

WriteLiteral(" class=\"alert alert-danger promonull\"");

WriteLiteral(" ng-show=\"ck.promonull\"");

WriteLiteral(">\r\n        <span>");

            
            #line 140 "..\..\Views\Checkout\_OrderSummary.cshtml"
         Write(LT("Checkout.Text.NullPromoMessage", "Please enter promo code!"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"summery-box\"");

WriteAttribute("ng-show", Tuple.Create(" ng-show=\"", 8452), Tuple.Create("\"", 8472)
            
            #line 143 "..\..\Views\Checkout\_OrderSummary.cshtml"
, Tuple.Create(Tuple.Create("", 8462), Tuple.Create<System.Object, System.Int32>(giftOrder
            
            #line default
            #line hidden
, 8462), false)
);

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral(">\r\n        <h4><i");

WriteLiteral(" class=\"fa fa-gift\"");

WriteLiteral("></i> ");

            
            #line 145 "..\..\Views\Checkout\_OrderSummary.cshtml"
                                  Write(LT("Checkout.Label.GiftForMe", "Who are you purchasing for today?"));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group padding-sm no-margin\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"control control--checkbox\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" ng-change=\"ck.purchaseFor(purchase)\"");

WriteLiteral(" class=\"ng-pristine ng-valid\"");

WriteLiteral(" ng-model=\"purchase.me\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" for=\"NewsLetterSubscribe\"");

WriteLiteral(">");

            
            #line 150 "..\..\Views\Checkout\_OrderSummary.cshtml"
                                        Write(LT("Checkout.Label.PurchasingForMe", "This order is just for me."));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"control__indicator\"");

WriteLiteral("></div>\r\n        </label>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group padding-sm no-margin\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"control control--checkbox \"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" ng-change=\"ck.purchaseFor(purchase)\"");

WriteLiteral(" class=\"ng-pristine ng-valid\"");

WriteLiteral(" ng-model=\"purchase.gift\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" for=\"NewsLetterSubscribe\"");

WriteLiteral(">");

            
            #line 157 "..\..\Views\Checkout\_OrderSummary.cshtml"
                                        Write(LT("Checkout.Label.PurchasingForGift", "This order contains a gift."));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div");

WriteLiteral(" class=\"control__indicator\"");

WriteLiteral("></div>\r\n        </label>\r\n    </div>\r\n\r\n</div>\r\n<!-- /.col-md-3 -->\r\n");

        }
    }
}
#pragma warning restore 1591
