#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    
    #line 15 "..\..\Views\B2B\MyCompany.cshtml"
    using Microsoft.Web.Mvc;
    
    #line default
    #line hidden
    using Omnicx.WebStore;
    using Omnicx.WebStore.Core;
    
    #line 17 "..\..\Views\B2B\MyCompany.cshtml"
    using Omnicx.WebStore.Core.Controllers;
    
    #line default
    #line hidden
    
    #line 19 "..\..\Views\B2B\MyCompany.cshtml"
    using Omnicx.WebStore.Framework.Helpers;
    
    #line default
    #line hidden
    
    #line 18 "..\..\Views\B2B\MyCompany.cshtml"
    using Omnicx.WebStore.Models.Commerce;
    
    #line default
    #line hidden
    
    #line 16 "..\..\Views\B2B\MyCompany.cshtml"
    using Omnicx.WebStore.Models.Enums;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/B2B/MyCompany.cshtml")]
    public partial class _Views_B2B_MyCompany_cshtml : Omnicx.WebStore.Core.Services.Infrastructure.CustomBaseViewPage<CustomerProfileModel>
    {
        public _Views_B2B_MyCompany_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\B2B\MyCompany.cshtml"
  
/*
    Name: My Company
    Purpose: Show Company Details
    Structure: /Views/B2B/MyCompany.cshtml
    Contains (Partial Views Used):
        a-/Views/Shared/_Layout.cshtml.cshtml   (For base Structure)
        b-/Views/Account/_SideNav.cshtml        (Navigation For Desktop and Big Screen)
        c-/Views/B2B/_AccountAlert.cshtml       (Validation Messages)

    Contained In (Where we Use this View):
     a-/Views/Account/_SideNav.cshtml        (Navigation Link Desktop and Big Screen)
    */

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 22 "..\..\Views\B2B\MyCompany.cshtml"
  
    var customerAccountForm = Html.Angular().ModelFor("b2b.model");
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "My Company";
    var userRole = SessionContext.CurrentUserRole;


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<section");

WriteLiteral(" ng-controller=\"b2bCtrl as b2b\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n                <li>\r\n                    <a");

WriteLiteral(" href=\"/\"");

WriteLiteral(">");

            
            #line 36 "..\..\Views\B2B\MyCompany.cshtml"
                           Write(LT("MyAccount.Links.Home", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </li>\r\n                <li>");

            
            #line 38 "..\..\Views\B2B\MyCompany.cshtml"
               Write(LT("MyAccount.Text.Name", "My Company"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-12 col-xs-12\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"panel-h2 hidden-xs\"");

WriteLiteral(">");

            
            #line 44 "..\..\Views\B2B\MyCompany.cshtml"
                                      Write(LT("MyAccount.Text.Name", "My Company"));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n        </div>\r\n    </div>\r\n    <!-- *** LEFT COLUMN ***\r\n    ____________" +
"_____________________________________________ -->\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-12 margin-bottom-lg visible-xs\"");

WriteLiteral(" id=\"exTab1\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-md-3 col-sm-4 col-xs-12 hidden-xs\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 54 "..\..\Views\B2B\MyCompany.cshtml"
       Write(Html.Partial("~/Views/Account/Layout2/_SideNav.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-md-9 col-sm-8 col-xs-12 clearfix\"");

WriteLiteral(" id=\"customer-account\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-sm-12 no-padding\"");

WriteLiteral(">\r\n\r\n                <form");

WriteLiteral(" name=\"changeForm\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(" ng-submit=\"b2b.saveCustomerDetail(b2b.model.companyDetail)\"");

WriteLiteral(" novalidate>\r\n\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(" ng-show=\"personalDetail\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 63 "..\..\Views\B2B\MyCompany.cshtml"
                       Write(Html.Partial("~/Views/B2B/_AccountAlert.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-6 col-xs-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 69 "..\..\Views\B2B\MyCompany.cshtml"
                           Write(customerAccountForm.FormGroupFor(x => x.CompanyDetail.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"col-sm-6 col-xs-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <label><strong>BusinessType</strong></label>\r\n" +
"                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"b2b.model.companyDetail.businessType\"");

WriteLiteral(" readonly />\r\n                            </div>\r\n                        </div> " +
"                    \r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-2 col-xs-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" ng-class=\"vm.getValidationClass()\"");

WriteLiteral(" form-group-validation=\"Title\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" for=\"Title\"");

WriteLiteral(" class=\"control-label ng-scope\"");

WriteLiteral(">");

            
            #line 83 "..\..\Views\B2B\MyCompany.cshtml"
                                                                                 Write(LT("MyAccount.Text.Title", "Title"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                    <select");

WriteLiteral(" name=\"Title\"");

WriteLiteral(" tabindex=\"1\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-label=\"Title\"");

WriteLiteral(" ng-model=\"b2b.model.companyDetail.title\"");

WriteLiteral(" ");

WriteLiteral(">\r\n                                        <option");

WriteLiteral(" ng-selected=\"b2b.model.companyDetail.title == null\"");

WriteLiteral(" value=\"\"");

WriteLiteral(">");

            
            #line 85 "..\..\Views\B2B\MyCompany.cshtml"
                                                                                                        Write(LT("MyAccount.Text.Title", "Title"));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                                        <option");

WriteLiteral(" value=\"Miss\"");

WriteLiteral(">Miss</option>\r\n                                        <option");

WriteLiteral(" value=\"Mr\"");

WriteLiteral(">Mr</option>\r\n                                        <option");

WriteLiteral(" value=\"Mrs\"");

WriteLiteral(">Mrs</option>\r\n                                    </select>\r\n                   " +
"             </div>\r\n                            </div>\r\n                       " +
" </div>\r\n                        <div");

WriteLiteral(" class=\"col-sm-4 col-xs-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 95 "..\..\Views\B2B\MyCompany.cshtml"
                           Write(customerAccountForm.FormGroupFor(x => x.CustomerAddress.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"col-sm-6 col-xs-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 100 "..\..\Views\B2B\MyCompany.cshtml"
                           Write(customerAccountForm.FormGroupFor(x => x.CustomerAddress.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"         </div>\r\n\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-2 col-xs-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" ng-class=\"vm.getValidationClass()\"");

WriteLiteral(" form-group-validation=\"Gender\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" for=\"Gender\"");

WriteLiteral(" class=\"control-label ng-scope\"");

WriteLiteral(">");

            
            #line 109 "..\..\Views\B2B\MyCompany.cshtml"
                                                                                  Write(LT("MyAccount.Text.Gender", "Gender"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                    <select");

WriteLiteral(" name=\"Gender\"");

WriteLiteral(" tabindex=\"1\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-label=\"Gender\"");

WriteLiteral(" ng-model=\"b2b.model.companyDetail.gender\"");

WriteLiteral(" ");

WriteLiteral(">\r\n                                        <option");

WriteLiteral(" ng-selected=\"b2b.model.companyDetail.gender == null\"");

WriteLiteral(" value=\"\"");

WriteLiteral(">");

            
            #line 111 "..\..\Views\B2B\MyCompany.cshtml"
                                                                                                         Write(LT("MyAccount.Text.Gender", "Gender"));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                                        <option");

WriteLiteral(" value=\"Male\"");

WriteLiteral(">Male</option>\r\n                                        <option");

WriteLiteral(" value=\"Female\"");

WriteLiteral(">Female</option>\r\n                                        <option");

WriteLiteral(" value=\"Other\"");

WriteLiteral(">Other</option>\r\n                                    </select>\r\n                 " +
"               </div>\r\n                            </div>\r\n                     " +
"   </div>\r\n                        <div");

WriteLiteral(" class=\"col-sm-4 col-xs-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <label><strong>CompanyName</strong></label>\r\n " +
"                               <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"b2b.model.companyDetail.companyName\"");

WriteLiteral(" readonly />                               \r\n                            </div>\r\n" +
"                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-sm-6 col-xs-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <label><strong>CompanyCode</strong></label>\r\n " +
"                               <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"b2b.model.companyDetail.companyCode\"");

WriteLiteral(" readonly />                                \r\n                            </div>\r" +
"\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 135 "..\..\Views\B2B\MyCompany.cshtml"
                           Write(customerAccountForm.FormGroupFor(x => x.CompanyDetail.Mobile));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 140 "..\..\Views\B2B\MyCompany.cshtml"
                           Write(customerAccountForm.FormGroupFor(x => x.CompanyDetail.Telephone));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"         </div>\r\n");

            
            #line 144 "..\..\Views\B2B\MyCompany.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 144 "..\..\Views\B2B\MyCompany.cshtml"
                     if (userRole == (CompanyUserRole.Admin))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-sm-12 margin-bottom-sm\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label><strong>Payment Methods</strong></l" +
"abel>\r\n                                </div>\r\n                            </div" +
">\r\n                            <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"control control--checkbox \"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" checked={{b2b.model.companyDetail.cheque}}");

WriteLiteral(" ng-model=\"b2b.model.companyDetail.cheque\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" for=\"Cheque\"");

WriteLiteral(">Cheque</label>\r\n                                    <div");

WriteLiteral(" class=\"control__indicator\"");

WriteLiteral("></div>\r\n                                </label>\r\n                            </" +
"div>\r\n                            <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"control control--checkbox\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" checked={{b2b.model.companyDetail.accountCredit}}");

WriteLiteral(" ng-model=\"b2b.model.companyDetail.accountCredit\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" for=\"AccountCredit\"");

WriteLiteral(">AccountCredit</label>\r\n                                    <div");

WriteLiteral(" class=\"control__indicator\"");

WriteLiteral("></div>\r\n                                </label>\r\n                            </" +
"div>\r\n                        </div>\r\n");

            
            #line 167 "..\..\Views\B2B\MyCompany.cshtml"
                    }                   

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"row margin-top-lg\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12 text-right\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"animate btn-primary\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-save\"");

WriteLiteral("></i>");

            
            #line 170 "..\..\Views\B2B\MyCompany.cshtml"
                                                                                                   Write(LT("MyAccount.Button.SaveChanges", "Save Changes"));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                        </div>\r\n                    </div>\r\n          " +
"      </form>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</section>\r\n\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script>\r\n        var saveCustomerUrl = \'");

            
            #line 182 "..\..\Views\B2B\MyCompany.cshtml"
                           Write(Html.BuildUrlFromExpression<B2BController>(c => c.SaveCustomerDetail(null)));

            
            #line default
            #line hidden
WriteLiteral("\';       \r\n        window.app.constant(\'b2bConfig\', {\r\n            saveCustomerUr" +
"l: saveCustomerUrl\r\n        });\r\n        window.app.constant(\'model\', ");

            
            #line 186 "..\..\Views\B2B\MyCompany.cshtml"
                                Write(Html.JsonFor(Model));

            
            #line default
            #line hidden
WriteLiteral(");\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
