#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Omnicx.WebStore;
    using Omnicx.WebStore.Core;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Common/Error500.cshtml")]
    public partial class _Views_Common_Error500_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Common_Error500_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Common\Error500.cshtml"
  
/*
    Name: Page Internal Error 500
    Purpose: Show This Error Page when found error 500
    Structure: /Views/Common/Error500.cshtml
    Contains (Partial Views Used):
        a-/Views/Shared/_Layout.cshtml    (For base Structure)

    Contained In (Where we Use this View):
    */

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 12 "..\..\Views\Common\Error500.cshtml"
  
    ViewBag.Title = "Error";
    Layout = "~/Views/Shared/_LayoutError.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"error-bg text-center\"");

WriteLiteral(">\r\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 499), Tuple.Create("\"", 538)
, Tuple.Create(Tuple.Create("", 505), Tuple.Create<System.Object, System.Int32>(Href("~/assets/theme/ocx/images/500.png")
, 505), false)
);

WriteLiteral(" />\r\n            <h3");

WriteLiteral(" class=\"error-h6\"");

WriteLiteral(">Internal Server Error</h3>\r\n            <p");

WriteLiteral(" class=\"error-desc\"");

WriteLiteral(">Ooops! It seems like something went wrong inside the system. We\'re on it !</p>\r\n" +
"            <p");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("><a");

WriteLiteral(" class=\"animate btn-bordered\"");

WriteAttribute("href", Tuple.Create(" href=\"", 784), Tuple.Create("\"", 793)
, Tuple.Create(Tuple.Create("", 791), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 791), false)
);

WriteLiteral(" role=\"button\"");

WriteLiteral(">Go Back to Home Page</a></p>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
